import type { IncomingHttpHeaders } from "node:http";
import { ProviderHttpClient, ProviderHttpError, nextLink } from "../httpClient.js";
import type { ChangeRequestRef, CheckState, CreateChangeRequest, DeliveryProvider, DeliveryProviderConfig, DeliveryState, NormalizedCheck, NormalizedReviewFeedback, OutboundReviewFeedback, Page, PageCursor, ProviderCapabilities, RemoteChangeRequest, RepositoryRef, UpdateChangeRequest, VerifiedDeliveryEvent, WriteOperationContext } from "../types.js";
import { DeliveryConflictError } from "../types.js";
import { parseWebhookJson, verifyGiteaWebhook } from "../webhook.js";
import { healthFromError, number, opaqueCursor, pagePath, query, repoParts, requiredToken, text } from "./common.js";
import { normalizeProviderWebUrl, requireProviderWebUrl } from "../providerUrl.js";

function apiBase(value: string): string { return /\/api\/v1\/?$/.test(value) ? value : `${value.replace(/\/$/, "")}/api/v1`; }
function state(value: any): DeliveryState { return value?.merged ? "merged" : value?.state === "open" && /^(?:WIP:|\[WIP\])/i.test(text(value?.title)) ? "draft" : value?.state === "open" ? "open" : value?.state === "closed" ? "closed" : "unknown"; }
function mapPull(configId: string, repositoryId: string, value: any): RemoteChangeRequest { return { providerConfigId: configId, repositoryId, number: number(value.number || value.index), remoteId: text(value.id || value.number || value.index), url: requireProviderWebUrl(value.html_url, "Gitea pull request"), title: text(value.title), body: text(value.body), state: state(value), headBranch: text(value.head?.ref || value.head?.name), baseBranch: text(value.base?.ref || value.base?.name), headSha: text(value.head?.sha), updatedAt: text(value.updated_at) || undefined, remoteVersion: value.content_version !== undefined ? String(value.content_version) : text(value.updated_at) || undefined, mergeReadiness: value.mergeable === false ? "blocked_conflict" : value.mergeable === true ? "ready" : "unknown" }; }
function checkState(value: unknown): CheckState { const state = String(value); if (["pending", "waiting", "queued", "requested"].includes(state)) return "queued"; if (["running", "in_progress"].includes(state)) return "running"; if (state === "success") return "success"; if (["failure", "error"].includes(state)) return "failure"; if (["cancelled", "canceled"].includes(state)) return "cancelled"; if (state === "skipped") return "skipped"; if (state === "warning") return "neutral"; return "unknown"; }

export class GiteaDeliveryProvider implements DeliveryProvider {
  readonly kind = "gitea" as const; readonly client: ProviderHttpClient; private actionsSupported: boolean | undefined;
  constructor(readonly config: DeliveryProviderConfig, client?: ProviderHttpClient) { this.client = client || new ProviderHttpClient(apiBase(config.baseUrl)); }
  private headers() { const token = requiredToken(this.config); return { token, headers: { Authorization: this.config.tokenKind === "bearer" ? `Bearer ${token}` : `token ${token}` } }; }
  private path(repository: RepositoryRef) { const { owner, name } = repoParts(repository); return `${encodeURIComponent(owner)}/${encodeURIComponent(name)}`; }
  async probe(repository: RepositoryRef, signal?: AbortSignal): Promise<ProviderCapabilities> { const checkedAt = Date.now(); try { const { token, headers } = this.headers(); const version = await this.client.request<any>({ path: "version", headers, signal, explicitSecrets: [token] }); await this.client.request({ path: `repos/${this.path(repository)}`, headers, signal, explicitSecrets: [token] }); try { await this.client.request({ path: `repos/${this.path(repository)}/actions/runs?limit=1`, headers, signal, explicitSecrets: [token] }); this.actionsSupported = true; } catch (error) { if (error instanceof ProviderHttpError && error.status === 404) this.actionsSupported = false; else throw error; } return { providerConfigId: this.config.id, kind: this.kind, version: text(version.data?.version), health: "online", authenticated: true, supports: { changeRequests: true, drafts: true, reviewThreads: true, reviewDecisions: true, checks: true, commitStatuses: true, actions: this.actionsSupported, webhooks: true, signedWebhooks: true, conditionalGets: false, atomicChangeRequestUpdate: true }, checkedAt }; } catch (error) { return { providerConfigId: this.config.id, kind: this.kind, health: healthFromError(error), authenticated: false, supports: { changeRequests: false, drafts: false, reviewThreads: false, reviewDecisions: false, checks: false, commitStatuses: false, actions: false, webhooks: true, signedWebhooks: true, conditionalGets: false, atomicChangeRequestUpdate: false }, checkedAt, error: error instanceof Error ? error.message : String(error) }; } }
  async findChangeRequests(repository: RepositoryRef, filter: { head?: string; base?: string; state?: DeliveryState }, page?: PageCursor, signal?: AbortSignal): Promise<Page<RemoteChangeRequest>> { const { token, headers } = this.headers(); const fallback = query(`repos/${this.path(repository)}/pulls`, { state: filter.state === "closed" || filter.state === "merged" ? "closed" : filter.state ? "open" : "all", base_branch: filter.base, page: 1, limit: 50 }); const response = await this.client.request<any[]>({ path: pagePath(this.client, page, fallback), headers, signal, explicitSecrets: [token] }); return { items: (Array.isArray(response.data) ? response.data : []).map((item) => mapPull(this.config.id, repository.remoteRepositoryId, item)).filter((item) => (!filter.head || item.headBranch === filter.head) && (!filter.base || item.baseBranch === filter.base)), nextCursor: opaqueCursor(nextLink(response.headers, apiBase(this.config.baseUrl))) }; }
  async getChangeRequest(ref: ChangeRequestRef, signal?: AbortSignal) { const { token, headers } = this.headers(); const response = await this.client.request<any>({ path: `repos/${this.path(ref)}/pulls/${ref.number}`, headers, signal, explicitSecrets: [token] }); return mapPull(this.config.id, ref.remoteRepositoryId, response.data); }
  async createChangeRequest(request: CreateChangeRequest, _context: WriteOperationContext, signal?: AbortSignal) { const { token, headers } = this.headers(); const title = request.draft && !/^(?:WIP:|\[WIP\])/i.test(request.title) ? `WIP: ${request.title}` : request.title; const response = await this.client.request<any>({ method: "POST", path: `repos/${this.path(request.repository)}/pulls`, headers, body: { title, body: request.body, head: request.headBranch, base: request.baseBranch }, signal, explicitSecrets: [token] }); return mapPull(this.config.id, request.repository.remoteRepositoryId, response.data); }
  async updateChangeRequest(ref: ChangeRequestRef, patch: UpdateChangeRequest, precondition: { expectedHeadSha: string; expectedRemoteVersion?: string }, _context: WriteOperationContext, signal?: AbortSignal) { const current = await this.getChangeRequest(ref, signal); if (current.headSha !== precondition.expectedHeadSha) throw new DeliveryConflictError("upstream_changed", `Expected head ${precondition.expectedHeadSha}, got ${current.headSha}`); if (precondition.expectedRemoteVersion && current.remoteVersion !== precondition.expectedRemoteVersion) throw new DeliveryConflictError("version_conflict", "Pull request changed since it was loaded"); const { token, headers } = this.headers(); const response = await this.client.request<any>({ method: "PATCH", path: `repos/${this.path(ref)}/pulls/${ref.number}`, headers, body: { ...(patch.title !== undefined ? { title: patch.title } : {}), ...(patch.body !== undefined ? { body: patch.body } : {}), ...(patch.baseBranch ? { base: patch.baseBranch } : {}), ...(patch.state ? { state: patch.state } : {}), ...(precondition.expectedRemoteVersion && /^\d+$/.test(precondition.expectedRemoteVersion) ? { content_version: Number(precondition.expectedRemoteVersion) } : {}) }, signal, explicitSecrets: [token] }); return mapPull(this.config.id, ref.remoteRepositoryId, response.data); }
  async listChecks(repository: RepositoryRef, headSha: string, page?: PageCursor, signal?: AbortSignal): Promise<Page<NormalizedCheck>> { const { token, headers } = this.headers(); const fallback = `repos/${this.path(repository)}/commits/${encodeURIComponent(headSha)}/statuses?limit=50`; const response = await this.client.request<any[]>({ path: pagePath(this.client, page, fallback), headers, signal, explicitSecrets: [token] }); const items = (Array.isArray(response.data) ? response.data : []).map((item): NormalizedCheck => ({ id: `gitea-status-${item.id}`, name: text(item.context), state: checkState(item.status || item.state), sha: text(item.sha) || headSha, url: normalizeProviderWebUrl(item.target_url), description: text(item.description) || undefined, startedAt: text(item.created_at) || undefined, completedAt: text(item.updated_at) || undefined })); if (!page?.value && this.actionsSupported !== false) try { const actions = await this.client.request<any>({ path: query(`repos/${this.path(repository)}/actions/runs`, { head_sha: headSha, limit: 50 }), headers, signal, explicitSecrets: [token] }); this.actionsSupported = true; for (const item of Array.isArray(actions.data?.workflow_runs) ? actions.data.workflow_runs : []) items.push({ id: `gitea-action-${item.id}`, name: text(item.name || item.display_title) || `Workflow ${item.id}`, state: checkState(item.status || item.conclusion), sha: text(item.head_sha) || headSha, url: normalizeProviderWebUrl(item.html_url), startedAt: text(item.run_started_at || item.created_at) || undefined, completedAt: text(item.updated_at) || undefined }); } catch (error) { if (error instanceof ProviderHttpError && error.status === 404) this.actionsSupported = false; else throw error; } return { items, nextCursor: opaqueCursor(nextLink(response.headers, apiBase(this.config.baseUrl))) }; }
  async listReviewFeedback(ref: ChangeRequestRef, _page?: PageCursor, signal?: AbortSignal): Promise<Page<NormalizedReviewFeedback>> { const { token, headers } = this.headers(); const comments = await this.client.request<any[]>({ path: `repos/${this.path(ref)}/issues/${ref.number}/comments`, headers, signal, explicitSecrets: [token] }); const reviews = await this.client.request<any[]>({ path: `repos/${this.path(ref)}/pulls/${ref.number}/reviews?limit=50`, headers, signal, explicitSecrets: [token] }); const items: NormalizedReviewFeedback[] = (Array.isArray(comments.data) ? comments.data : []).map((item): NormalizedReviewFeedback => ({ id: `gitea-comment-${item.id}`, kind: "comment", author: text(item.user?.login) || undefined, body: text(item.body), url: normalizeProviderWebUrl(item.html_url), updatedAt: text(item.updated_at) || undefined })); for (const item of Array.isArray(reviews.data) ? reviews.data : []) items.push({ id: `gitea-review-${item.id}`, kind: text(item.state || item.type).toLowerCase().includes("approve") ? "approval" : "comment", author: text(item.user?.login) || undefined, body: text(item.body), state: text(item.state || item.type).toLowerCase().includes("approve") ? "approved" : text(item.state || item.type).toLowerCase().includes("reject") ? "changes_requested" : "commented", url: normalizeProviderWebUrl(item.html_url), headSha: text(item.commit_id) || undefined, updatedAt: text(item.updated_at || item.submitted_at) || undefined }); return { items }; }
  async createReviewFeedback(ref: ChangeRequestRef, feedback: OutboundReviewFeedback, _context: WriteOperationContext, signal?: AbortSignal): Promise<NormalizedReviewFeedback> { const { token, headers } = this.headers(); const response = await this.client.request<any>({ method: "POST", path: `repos/${this.path(ref)}/pulls/${ref.number}/reviews`, headers, body: { body: feedback.body, commit_id: feedback.headSha, event: feedback.decision === "approve" ? "APPROVE" : feedback.decision === "request_changes" ? "REQUEST_CHANGES" : "COMMENT" }, signal, explicitSecrets: [token] }); return { id: `gitea-review-${response.data?.id}`, kind: feedback.decision === "approve" ? "approval" : "comment", author: text(response.data?.user?.login) || undefined, body: text(response.data?.body), state: feedback.decision === "approve" ? "approved" : feedback.decision === "request_changes" ? "changes_requested" : "commented", url: normalizeProviderWebUrl(response.data?.html_url), headSha: text(response.data?.commit_id) || undefined, updatedAt: text(response.data?.updated_at || response.data?.submitted_at) || undefined }; }
  verifyAndNormalizeWebhook(rawBody: Buffer, headers: IncomingHttpHeaders, secret: string): VerifiedDeliveryEvent { const identity = verifyGiteaWebhook(rawBody, headers, secret); const body = parseWebhookJson(rawBody); const workflow = body.workflow_run || body.workflow_job; const status = body.sha && body.context ? body : undefined; const comment = body.comment || body.review; return { providerConfigId: this.config.id, deliveryId: identity.deliveryId, event: identity.event, action: text(body.action) || undefined, repositoryId: text(body.repository?.full_name || body.repository?.id) || undefined, changeRequestNumber: number(body.pull_request?.number || body.number) || undefined, headSha: text(body.pull_request?.head?.sha || body.commit_id || body.sha || workflow?.head_sha) || undefined, ...((workflow || status) ? { check: { id: `gitea-${workflow ? "workflow" : "status"}-${workflow?.id || status?.id}`, name: text(workflow?.name || status?.context), state: checkState(workflow?.status || workflow?.conclusion || status?.state), sha: text(workflow?.head_sha || status?.sha), url: normalizeProviderWebUrl(workflow?.html_url || status?.target_url) } } : {}), ...(comment ? { feedback: { id: `gitea-feedback-${comment.id}`, kind: body.review ? "approval" : body.pull_request && comment.path ? "inline_comment" : "comment", author: text(body.sender?.login || comment.user?.login) || undefined, body: text(comment.body), state: text(comment.type).toLowerCase() === "approved" ? "approved" : text(comment.type).toLowerCase() === "rejected" ? "changes_requested" : "commented", url: normalizeProviderWebUrl(comment.html_url), path: text(comment.path) || undefined, line: number(comment.line) || undefined, headSha: text(body.commit_id || body.pull_request?.head?.sha) || undefined, updatedAt: text(comment.updated_at || comment.submitted_at) || undefined } } : {}), receivedAt: Date.now() }; }
}
