import type { IncomingHttpHeaders } from "node:http";
import { ProviderHttpClient, nextLink } from "../httpClient.js";
import type { ChangeRequestRef, CheckState, CreateChangeRequest, DeliveryProvider, DeliveryProviderConfig, DeliveryState, NormalizedCheck, NormalizedReviewFeedback, OutboundReviewFeedback, Page, PageCursor, ProviderCapabilities, RemoteChangeRequest, RepositoryRef, UpdateChangeRequest, VerifiedDeliveryEvent, WriteOperationContext } from "../types.js";
import { DeliveryConflictError } from "../types.js";
import { parseWebhookJson, verifyGithubWebhook } from "../webhook.js";
import { healthFromError, number, opaqueCursor, pagePath, query, repoParts, requiredToken, text } from "./common.js";
import { firstProviderWebUrl, normalizeProviderWebUrl, requireProviderWebUrl } from "../providerUrl.js";

const DEFAULT_VERSION = "2026-03-10";
function state(value: any): DeliveryState { return value?.merged ? "merged" : value?.draft && value?.state === "open" ? "draft" : value?.state === "open" ? "open" : value?.state === "closed" ? "closed" : "unknown"; }
function readiness(value: any) { return value?.mergeable === false ? "blocked_conflict" as const : value?.mergeable === true ? "ready" as const : "checking" as const; }
function mapPull(configId: string, repositoryId: string, value: any): RemoteChangeRequest {
  return { providerConfigId: configId, repositoryId, number: number(value.number), remoteId: text(value.id || value.node_id || value.number), url: requireProviderWebUrl(value.html_url, "GitHub pull request"), title: text(value.title), body: text(value.body), state: state(value), headBranch: text(value.head?.ref), baseBranch: text(value.base?.ref), headSha: text(value.head?.sha), updatedAt: text(value.updated_at) || undefined, remoteVersion: text(value.updated_at) || undefined, mergeReadiness: readiness(value) };
}
function checkState(status: unknown, conclusion: unknown): CheckState {
  if (status === "queued" || status === "requested" || status === "waiting") return "queued";
  if (status === "in_progress" || status === "pending") return "running";
  if (conclusion === "success" || status === "success") return "success";
  if (["failure", "timed_out", "action_required", "startup_failure", "error"].includes(String(conclusion || status))) return "failure";
  if (conclusion === "cancelled") return "cancelled";
  if (conclusion === "skipped") return "skipped";
  if (["neutral", "stale"].includes(String(conclusion))) return "neutral";
  return "unknown";
}
export class GithubDeliveryProvider implements DeliveryProvider {
  readonly kind = "github" as const;
  readonly client: ProviderHttpClient;
  constructor(readonly config: DeliveryProviderConfig, client?: ProviderHttpClient) { this.client = client || new ProviderHttpClient(config.baseUrl); }
  private headers() { const token = requiredToken(this.config); return { token, headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json", "X-GitHub-Api-Version": this.config.apiVersion || DEFAULT_VERSION, "User-Agent": "CrownForge-Delivery/1.0" } }; }
  async probe(repository: RepositoryRef, signal?: AbortSignal): Promise<ProviderCapabilities> {
    const checkedAt = Date.now();
    try {
      const { token, headers } = this.headers();
      const versions = await this.client.request<string[]>({ path: "versions", headers, signal, explicitSecrets: [token] });
      const selected = this.config.apiVersion || DEFAULT_VERSION;
      if (Array.isArray(versions.data) && !versions.data.includes(selected)) throw new Error(`GitHub API version is unsupported: ${selected}`);
      const { owner, name } = repoParts(repository);
      await this.client.request({ path: `repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}`, headers, signal, explicitSecrets: [token] });
      return { providerConfigId: this.config.id, kind: this.kind, version: selected, health: "online", authenticated: true, supports: { changeRequests: true, drafts: true, reviewThreads: true, reviewDecisions: true, checks: true, commitStatuses: true, actions: true, webhooks: true, signedWebhooks: true, conditionalGets: true, atomicChangeRequestUpdate: false }, checkedAt };
    } catch (error) { return { providerConfigId: this.config.id, kind: this.kind, health: healthFromError(error), authenticated: false, supports: { changeRequests: false, drafts: false, reviewThreads: false, reviewDecisions: false, checks: false, commitStatuses: false, actions: false, webhooks: true, signedWebhooks: true, conditionalGets: true, atomicChangeRequestUpdate: false }, checkedAt, error: error instanceof Error ? error.message : String(error) }; }
  }
  async findChangeRequests(repository: RepositoryRef, filter: { head?: string; base?: string; state?: DeliveryState }, page?: PageCursor, signal?: AbortSignal): Promise<Page<RemoteChangeRequest>> {
    const { owner, name } = repoParts(repository); const { token, headers } = this.headers();
    const fallback = query(`repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/pulls`, { state: filter.state === "closed" || filter.state === "merged" ? "closed" : filter.state ? "open" : "all", head: filter.head, base: filter.base, per_page: 100 });
    const response = await this.client.request<any[]>({ path: pagePath(this.client, page, fallback), headers, signal, explicitSecrets: [token] });
    return { items: (Array.isArray(response.data) ? response.data : []).map((item) => mapPull(this.config.id, repository.remoteRepositoryId, item)).filter((item) => (!filter.head || item.headBranch === filter.head || `${owner}:${item.headBranch}` === filter.head) && (!filter.base || item.baseBranch === filter.base)), nextCursor: opaqueCursor(nextLink(response.headers, this.config.baseUrl)), etag: response.headers.get("etag") || undefined };
  }
  async getChangeRequest(ref: ChangeRequestRef, signal?: AbortSignal) { const { owner, name } = repoParts(ref); const { token, headers } = this.headers(); const response = await this.client.request<any>({ path: `repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/pulls/${ref.number}`, headers, signal, explicitSecrets: [token] }); return mapPull(this.config.id, ref.remoteRepositoryId, response.data); }
  async createChangeRequest(request: CreateChangeRequest, _context: WriteOperationContext, signal?: AbortSignal) { const { owner, name } = repoParts(request.repository); const { token, headers } = this.headers(); const response = await this.client.request<any>({ method: "POST", path: `repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/pulls`, headers, body: { title: request.title, body: request.body, head: request.headBranch, base: request.baseBranch, draft: request.draft === true }, signal, explicitSecrets: [token] }); return mapPull(this.config.id, request.repository.remoteRepositoryId, response.data); }
  async updateChangeRequest(ref: ChangeRequestRef, patch: UpdateChangeRequest, precondition: { expectedHeadSha: string; expectedRemoteVersion?: string }, _context: WriteOperationContext, signal?: AbortSignal) { const current = await this.getChangeRequest(ref, signal); if (current.headSha !== precondition.expectedHeadSha) throw new DeliveryConflictError("upstream_changed", `Expected head ${precondition.expectedHeadSha}, got ${current.headSha}`); if (precondition.expectedRemoteVersion && current.remoteVersion !== precondition.expectedRemoteVersion) throw new DeliveryConflictError("version_conflict", "Pull request changed since it was loaded"); const { owner, name } = repoParts(ref); const { token, headers } = this.headers(); const response = await this.client.request<any>({ method: "PATCH", path: `repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/pulls/${ref.number}`, headers, body: { ...(patch.title !== undefined ? { title: patch.title } : {}), ...(patch.body !== undefined ? { body: patch.body } : {}), ...(patch.baseBranch ? { base: patch.baseBranch } : {}), ...(patch.state ? { state: patch.state } : {}) }, signal, explicitSecrets: [token] }); return mapPull(this.config.id, ref.remoteRepositoryId, response.data); }
  async listChecks(repository: RepositoryRef, headSha: string, page?: PageCursor, signal?: AbortSignal): Promise<Page<NormalizedCheck>> { const { owner, name } = repoParts(repository); const { token, headers } = this.headers(); const fallback = `repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/commits/${encodeURIComponent(headSha)}/check-runs?per_page=100&filter=all`; const response = await this.client.request<any>({ path: pagePath(this.client, page, fallback), headers, signal, explicitSecrets: [token] }); const checks = (Array.isArray(response.data?.check_runs) ? response.data.check_runs : []).map((item: any): NormalizedCheck => ({ id: `github-check-${item.id}`, name: text(item.name), state: checkState(item.status, item.conclusion), sha: text(item.head_sha) || headSha, url: firstProviderWebUrl(item.html_url, item.details_url), description: text(item.output?.summary) || undefined, startedAt: text(item.started_at) || undefined, completedAt: text(item.completed_at) || undefined })); if (!page?.value) { const statuses = await this.client.request<any>({ path: `repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/commits/${encodeURIComponent(headSha)}/status`, headers, signal, explicitSecrets: [token] }); for (const item of Array.isArray(statuses.data?.statuses) ? statuses.data.statuses : []) checks.push({ id: `github-status-${item.id}`, name: text(item.context), state: checkState(item.state, item.state), sha: headSha, url: normalizeProviderWebUrl(item.target_url), description: text(item.description) || undefined }); } return { items: checks, nextCursor: opaqueCursor(nextLink(response.headers, this.config.baseUrl)), etag: response.headers.get("etag") || undefined }; }
  async listReviewFeedback(ref: ChangeRequestRef, page?: PageCursor, signal?: AbortSignal): Promise<Page<NormalizedReviewFeedback>> { const { owner, name } = repoParts(ref); const { token, headers } = this.headers(); const fallback = `repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/pulls/${ref.number}/comments?per_page=100`; const response = await this.client.request<any[]>({ path: pagePath(this.client, page, fallback), headers, signal, explicitSecrets: [token] }); return { items: (Array.isArray(response.data) ? response.data : []).map((item): NormalizedReviewFeedback => ({ id: `github-review-comment-${item.id}`, kind: "inline_comment", author: text(item.user?.login) || undefined, body: text(item.body), url: normalizeProviderWebUrl(item.html_url), path: text(item.path) || undefined, line: number(item.line || item.original_line) || undefined, headSha: text(item.commit_id) || undefined, updatedAt: text(item.updated_at) || undefined })), nextCursor: opaqueCursor(nextLink(response.headers, this.config.baseUrl)) };
  }
  async createReviewFeedback(ref: ChangeRequestRef, feedback: OutboundReviewFeedback, _context: WriteOperationContext, signal?: AbortSignal): Promise<NormalizedReviewFeedback> { const { owner, name } = repoParts(ref); const { token, headers } = this.headers(); const response = await this.client.request<any>({ method: "POST", path: `repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/pulls/${ref.number}/reviews`, headers, body: { body: feedback.body, event: feedback.decision === "approve" ? "APPROVE" : feedback.decision === "request_changes" ? "REQUEST_CHANGES" : "COMMENT", commit_id: feedback.headSha, ...(feedback.path && feedback.line ? { comments: [{ path: feedback.path, line: feedback.line, side: "RIGHT", body: feedback.body }] } : {}) }, signal, explicitSecrets: [token] }); return { id: `github-review-${response.data?.id}`, kind: feedback.path ? "inline_comment" : "comment", author: text(response.data?.user?.login) || undefined, body: text(response.data?.body), state: text(response.data?.state).toLowerCase() === "approved" ? "approved" : text(response.data?.state).toLowerCase() === "changes_requested" ? "changes_requested" : "commented", url: normalizeProviderWebUrl(response.data?.html_url), headSha: text(response.data?.commit_id) || undefined, updatedAt: text(response.data?.submitted_at) || undefined }; }
  verifyAndNormalizeWebhook(rawBody: Buffer, headers: IncomingHttpHeaders, secret: string): VerifiedDeliveryEvent { const identity = verifyGithubWebhook(rawBody, headers, secret); const body = parseWebhookJson(rawBody); const pull = body.pull_request; const check = body.check_run; const comment = body.comment; return { providerConfigId: this.config.id, deliveryId: identity.deliveryId, event: identity.event, action: text(body.action) || undefined, repositoryId: text(body.repository?.full_name || body.repository?.id) || undefined, changeRequestNumber: number(pull?.number || body.issue?.number) || undefined, headSha: text(pull?.head?.sha || check?.head_sha || body.sha) || undefined, ...(check ? { check: { id: `github-check-${check.id}`, name: text(check.name), state: checkState(check.status, check.conclusion), sha: text(check.head_sha), url: firstProviderWebUrl(check.html_url, check.details_url) } } : {}), ...(comment ? { feedback: { id: `github-comment-${comment.id}`, kind: identity.event === "pull_request_review_comment" ? "inline_comment" : "comment", author: text(comment.user?.login) || undefined, body: text(comment.body), url: normalizeProviderWebUrl(comment.html_url), path: text(comment.path) || undefined, line: number(comment.line) || undefined, headSha: text(comment.commit_id) || undefined, updatedAt: text(comment.updated_at) || undefined } } : {}), receivedAt: Date.now() }; }
}
