import type { IncomingHttpHeaders } from "node:http";
import { ProviderHttpClient, nextLink } from "../httpClient.js";
import type { ChangeRequestRef, CheckState, CreateChangeRequest, DeliveryProvider, DeliveryProviderConfig, DeliveryState, NormalizedCheck, NormalizedReviewFeedback, OutboundReviewFeedback, Page, PageCursor, ProviderCapabilities, RemoteChangeRequest, RepositoryRef, UpdateChangeRequest, VerifiedDeliveryEvent, WriteOperationContext } from "../types.js";
import { DeliveryConflictError } from "../types.js";
import { parseWebhookJson, verifyGitlabWebhook } from "../webhook.js";
import { healthFromError, number, opaqueCursor, pagePath, query, requiredToken, text } from "./common.js";
import { normalizeProviderWebUrl, requireProviderWebUrl } from "../providerUrl.js";

function apiBase(value: string): string { return /\/api\/v4\/?$/.test(value) ? value : `${value.replace(/\/$/, "")}/api/v4`; }
function state(value: any): DeliveryState { return value?.state === "merged" ? "merged" : value?.draft || /^\s*(?:draft:|wip:)/i.test(text(value?.title)) ? "draft" : value?.state === "opened" ? "open" : value?.state === "closed" ? "closed" : "unknown"; }
function readiness(value: any) { const status = text(value?.detailed_merge_status || value?.merge_status); return status === "mergeable" || status === "can_be_merged" ? "ready" as const : status === "conflict" || status === "cannot_be_merged" ? "blocked_conflict" as const : ["checking", "approvals_syncing", "unchecked"].includes(status) ? "checking" as const : status.includes("ci_") ? "blocked_checks" as const : status.includes("approval") || status.includes("discussion") ? "blocked_review" as const : "unknown" as const; }
function mapMr(configId: string, repositoryId: string, value: any): RemoteChangeRequest { return { providerConfigId: configId, repositoryId, number: number(value.iid), remoteId: text(value.id || value.iid), url: requireProviderWebUrl(value.web_url, "GitLab merge request"), title: text(value.title), body: text(value.description), state: state(value), headBranch: text(value.source_branch), baseBranch: text(value.target_branch), headSha: text(value.sha || value.diff_refs?.head_sha || value.head_pipeline?.sha), updatedAt: text(value.updated_at) || undefined, remoteVersion: text(value.updated_at) || undefined, mergeReadiness: readiness(value) }; }
function checkState(value: unknown): CheckState { const state = String(value); if (["created", "waiting_for_resource", "preparing", "pending", "scheduled", "waiting_for_callback"].includes(state)) return "queued"; if (["running", "canceling"].includes(state)) return "running"; if (state === "success") return "success"; if (state === "failed") return "failure"; if (state === "canceled") return "cancelled"; if (["skipped", "manual"].includes(state)) return "skipped"; return "unknown"; }

export class GitlabDeliveryProvider implements DeliveryProvider {
  readonly kind = "gitlab" as const;
  readonly client: ProviderHttpClient;
  constructor(readonly config: DeliveryProviderConfig, client?: ProviderHttpClient) { this.client = client || new ProviderHttpClient(apiBase(config.baseUrl)); }
  private headers(): { token: string; headers: Record<string, string> } { const token = requiredToken(this.config); return { token, headers: this.config.tokenKind === "bearer" ? { Authorization: `Bearer ${token}` } : { "PRIVATE-TOKEN": token } }; }
  private project(repository: RepositoryRef) { return encodeURIComponent(repository.remoteRepositoryId); }
  async probe(repository: RepositoryRef, signal?: AbortSignal): Promise<ProviderCapabilities> { const checkedAt = Date.now(); try { const { token, headers } = this.headers(); const metadata = await this.client.request<any>({ path: "version", headers, signal, explicitSecrets: [token] }); await this.client.request({ path: `projects/${this.project(repository)}`, headers, signal, explicitSecrets: [token] }); const version = text(metadata.data?.version); const major = Number(version.match(/^\d+/)?.[0] || 0); return { providerConfigId: this.config.id, kind: this.kind, version, health: "online", authenticated: true, supports: { changeRequests: true, drafts: major >= 19, reviewThreads: true, reviewDecisions: true, checks: true, commitStatuses: true, actions: true, webhooks: true, signedWebhooks: major >= 19, conditionalGets: true, atomicChangeRequestUpdate: false }, checkedAt }; } catch (error) { return { providerConfigId: this.config.id, kind: this.kind, health: healthFromError(error), authenticated: false, supports: { changeRequests: false, drafts: false, reviewThreads: false, reviewDecisions: false, checks: false, commitStatuses: false, actions: false, webhooks: true, signedWebhooks: false, conditionalGets: true, atomicChangeRequestUpdate: false }, checkedAt, error: error instanceof Error ? error.message : String(error) }; } }
  async findChangeRequests(repository: RepositoryRef, filter: { head?: string; base?: string; state?: DeliveryState }, page?: PageCursor, signal?: AbortSignal): Promise<Page<RemoteChangeRequest>> { const { token, headers } = this.headers(); const fallback = query(`projects/${this.project(repository)}/merge_requests`, { scope: "all", state: filter.state === "closed" || filter.state === "merged" ? filter.state : filter.state ? "opened" : "all", source_branch: filter.head, target_branch: filter.base, per_page: 100 }); const response = await this.client.request<any[]>({ path: pagePath(this.client, page, fallback), headers, signal, explicitSecrets: [token] }); return { items: (Array.isArray(response.data) ? response.data : []).map((item) => mapMr(this.config.id, repository.remoteRepositoryId, item)), nextCursor: opaqueCursor(nextLink(response.headers, apiBase(this.config.baseUrl))), etag: response.headers.get("etag") || undefined }; }
  async getChangeRequest(ref: ChangeRequestRef, signal?: AbortSignal) { const { token, headers } = this.headers(); const response = await this.client.request<any>({ path: `projects/${this.project(ref)}/merge_requests/${ref.number}`, headers, signal, explicitSecrets: [token] }); return mapMr(this.config.id, ref.remoteRepositoryId, response.data); }
  async createChangeRequest(request: CreateChangeRequest, _context: WriteOperationContext, signal?: AbortSignal) { const { token, headers } = this.headers(); const title = request.draft && !/^\s*(?:draft:|wip:)/i.test(request.title) ? `Draft: ${request.title}` : request.title; const response = await this.client.request<any>({ method: "POST", path: `projects/${this.project(request.repository)}/merge_requests`, headers, body: { source_branch: request.headBranch, target_branch: request.baseBranch, title, description: request.body }, signal, explicitSecrets: [token] }); return mapMr(this.config.id, request.repository.remoteRepositoryId, response.data); }
  async updateChangeRequest(ref: ChangeRequestRef, patch: UpdateChangeRequest, precondition: { expectedHeadSha: string; expectedRemoteVersion?: string }, _context: WriteOperationContext, signal?: AbortSignal) { const current = await this.getChangeRequest(ref, signal); if (current.headSha !== precondition.expectedHeadSha) throw new DeliveryConflictError("upstream_changed", `Expected head ${precondition.expectedHeadSha}, got ${current.headSha}`); if (precondition.expectedRemoteVersion && current.remoteVersion !== precondition.expectedRemoteVersion) throw new DeliveryConflictError("version_conflict", "Merge request changed since it was loaded"); const { token, headers } = this.headers(); const response = await this.client.request<any>({ method: "PUT", path: `projects/${this.project(ref)}/merge_requests/${ref.number}`, headers, body: { ...(patch.title !== undefined ? { title: patch.title } : {}), ...(patch.body !== undefined ? { description: patch.body } : {}), ...(patch.baseBranch ? { target_branch: patch.baseBranch } : {}), ...(patch.state ? { state_event: patch.state === "closed" ? "close" : "reopen" } : {}) }, signal, explicitSecrets: [token] }); return mapMr(this.config.id, ref.remoteRepositoryId, response.data); }
  async listChecks(repository: RepositoryRef, headSha: string, page?: PageCursor, signal?: AbortSignal): Promise<Page<NormalizedCheck>> { const { token, headers } = this.headers(); const fallback = query(`projects/${this.project(repository)}/pipelines`, { sha: headSha, per_page: 100, order_by: "id", sort: "desc" }); const response = await this.client.request<any[]>({ path: pagePath(this.client, page, fallback), headers, signal, explicitSecrets: [token] }); const items = (Array.isArray(response.data) ? response.data : []).map((item): NormalizedCheck => ({ id: `gitlab-pipeline-${item.id}`, name: text(item.name) || `Pipeline ${item.id}`, state: checkState(item.status), sha: text(item.sha) || headSha, url: normalizeProviderWebUrl(item.web_url), startedAt: text(item.started_at || item.created_at) || undefined, completedAt: text(item.finished_at) || undefined })); if (!page?.value) { const statuses = await this.client.request<any[]>({ path: `projects/${this.project(repository)}/repository/commits/${encodeURIComponent(headSha)}/statuses?per_page=100`, headers, signal, explicitSecrets: [token] }); for (const item of Array.isArray(statuses.data) ? statuses.data : []) items.push({ id: `gitlab-status-${item.id}`, name: text(item.name), state: checkState(item.status), sha: text(item.sha) || headSha, url: normalizeProviderWebUrl(item.target_url), description: text(item.description) || undefined, startedAt: text(item.started_at) || undefined, completedAt: text(item.finished_at) || undefined }); } return { items, nextCursor: opaqueCursor(nextLink(response.headers, apiBase(this.config.baseUrl))), etag: response.headers.get("etag") || undefined }; }
  async listReviewFeedback(ref: ChangeRequestRef, page?: PageCursor, signal?: AbortSignal): Promise<Page<NormalizedReviewFeedback>> { const { token, headers } = this.headers(); const fallback = `projects/${this.project(ref)}/merge_requests/${ref.number}/discussions?per_page=100`; const response = await this.client.request<any[]>({ path: pagePath(this.client, page, fallback), headers, signal, explicitSecrets: [token] }); const items: NormalizedReviewFeedback[] = []; for (const discussion of Array.isArray(response.data) ? response.data : []) for (const note of Array.isArray(discussion.notes) ? discussion.notes : []) if (!note.system) items.push({ id: `gitlab-note-${note.id}`, kind: note.position ? "inline_comment" : "comment", author: text(note.author?.username) || undefined, body: text(note.body), url: normalizeProviderWebUrl(note.web_url), path: text(note.position?.new_path || note.position?.old_path) || undefined, line: number(note.position?.new_line || note.position?.old_line) || undefined, headSha: text(note.position?.head_sha) || undefined, updatedAt: text(note.updated_at) || undefined }); return { items, nextCursor: opaqueCursor(nextLink(response.headers, apiBase(this.config.baseUrl))) }; }
  async createReviewFeedback(ref: ChangeRequestRef, feedback: OutboundReviewFeedback, _context: WriteOperationContext, signal?: AbortSignal): Promise<NormalizedReviewFeedback> { const { token, headers } = this.headers(); if (feedback.decision === "approve") { const response = await this.client.request<any>({ method: "POST", path: `projects/${this.project(ref)}/merge_requests/${ref.number}/approve`, headers, body: { sha: feedback.headSha }, signal, explicitSecrets: [token] }); return { id: `gitlab-approval-${response.data?.id || ref.number}`, kind: "approval", body: feedback.body, state: "approved", headSha: feedback.headSha }; } const response = await this.client.request<any>({ method: "POST", path: `projects/${this.project(ref)}/merge_requests/${ref.number}/notes`, headers, body: { body: feedback.body }, signal, explicitSecrets: [token] }); return { id: `gitlab-note-${response.data?.id}`, kind: "comment", author: text(response.data?.author?.username) || undefined, body: text(response.data?.body), url: normalizeProviderWebUrl(response.data?.web_url), updatedAt: text(response.data?.updated_at) || undefined }; }
  verifyAndNormalizeWebhook(rawBody: Buffer, headers: IncomingHttpHeaders, secret: string): VerifiedDeliveryEvent { const identity = verifyGitlabWebhook(rawBody, headers, secret); const body = parseWebhookJson(rawBody); const attrs = body.object_attributes || {}; const project = body.project || {}; const commit = body.commit || {}; const pipelineLike = body.object_kind === "pipeline" || body.object_kind === "build"; const note = body.object_kind === "note" ? attrs : undefined; return { providerConfigId: this.config.id, deliveryId: identity.deliveryId, event: text(body.object_kind) || identity.event, action: text(attrs.action) || undefined, repositoryId: text(project.path_with_namespace || project.id) || undefined, changeRequestNumber: number(body.merge_request?.iid || attrs.iid) || undefined, headSha: text(body.merge_request?.last_commit?.id || attrs.last_commit?.id || attrs.sha || commit.id) || undefined, ...(pipelineLike ? { check: { id: `gitlab-${body.object_kind}-${attrs.id}`, name: text(attrs.name) || `${body.object_kind} ${attrs.id}`, state: checkState(attrs.status), sha: text(attrs.sha || commit.id), url: normalizeProviderWebUrl(attrs.url) } } : {}), ...(note ? { feedback: { id: `gitlab-note-${note.id}`, kind: note.position ? "inline_comment" : "comment", author: text(body.user?.username) || undefined, body: text(note.note), url: normalizeProviderWebUrl(note.url), path: text(note.position?.new_path || note.position?.old_path) || undefined, line: number(note.position?.new_line || note.position?.old_line) || undefined, headSha: text(body.merge_request?.last_commit?.id) || undefined, updatedAt: text(note.updated_at) || undefined } } : {}), receivedAt: Date.now() }; }
}
