import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { applyChangeSetDecision, captureChangeSet, changeSetReviewRevision, preflightChangeSetDecision } from "./changeSets.js";
import { createManagedWorktree, removeManagedWorktree } from "./worktrees.js";
import { ReviewFindingStore } from "./reviewFindingStore.js";
import { hasCompletedChangeSetReview, listChangeSetReviewRuns, reconcileChangeSetReviewRuns, reconstructChangeSetCheckout, scheduleChangeSetReview, setChangeSetReviewRunnerForTests } from "./changeSetReviewRun.js";
import { SessionManager } from "../auth/sessionManager.js";

function git(dir: string, args: string[]) { return execFileSync("git", ["-C", dir, ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim(); }
function repository(t: test.TestContext) { const dir = fs.mkdtempSync(path.join(os.tmpdir(), "crewforge-review-run-")); t.after(() => fs.rmSync(dir, { recursive: true, force: true })); git(dir, ["init"]); git(dir, ["config", "user.email", "test@example.com"]); git(dir, ["config", "user.name", "Test"]); fs.writeFileSync(path.join(dir, "a.txt"), "base\n"); git(dir, ["add", "."]); git(dir, ["commit", "-m", "base"]); return dir; }
async function settle(dir: string, id: string) { for (let i = 0; i < 100; i += 1) { const run = listChangeSetReviewRuns(dir, id)[0]; if (run?.status === "completed" || run?.status === "failed") return run; await new Promise((resolve) => setTimeout(resolve, 10)); } throw new Error("review did not settle"); }

test("reconstructs only the persisted immutable patch and rejects corrupt or legacy blobs", (t) => { const dir = repository(t); const wt = createManagedWorktree(dir, { name: "review" }); fs.writeFileSync(path.join(wt.path, "a.txt"), "reviewed\n"); git(wt.path, ["add", "a.txt"]); git(wt.path, ["commit", "-m", "change"]); const set = captureChangeSet(dir, wt.id, { ok: true }); fs.writeFileSync(path.join(wt.path, "a.txt"), "writer mutable\n"); const checkout = reconstructChangeSetCheckout(dir, set); try { assert.equal(fs.readFileSync(path.join(checkout.checkoutDir, "a.txt"), "utf8"), "reviewed\n"); } finally { checkout.cleanup(); } const blob = path.join(dir, ".history", "change-sets", set.patchBlob!); fs.writeFileSync(blob, "corrupt"); assert.throws(() => reconstructChangeSetCheckout(dir, set), /digest/i); assert.throws(() => reconstructChangeSetCheckout(dir, { ...set, schemaVersion: 1, patchBlob: undefined }), /Legacy/i); });

test("existing corrupt review-run state fails closed and is preserved", (t) => {
  const dir = repository(t); const target = path.join(dir, ".history", "change-set-review-runs.json");
  fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, "{corrupt-review-runs");
  assert.throws(() => listChangeSetReviewRuns(dir), (error: unknown) => (error as { code?: string }).code === "change_set_review_persistence_invalid");
  assert.equal(fs.readFileSync(target, "utf8"), "{corrupt-review-runs");
});

test("independent zero-finding review is required for integration and review runs bind server identities", async (t) => { const dir = repository(t); const wt = createManagedWorktree(dir, { name: "review", ownerId: "writer" }); fs.writeFileSync(path.join(wt.path, "a.txt"), "reviewed\n"); git(wt.path, ["add", "a.txt"]); git(wt.path, ["commit", "-m", "change"]); const set = captureChangeSet(dir, wt.id, { ok: true }); assert.equal(preflightChangeSetDecision(dir, set, "apply").applicable, false); setChangeSetReviewRunnerForTests(async () => []); t.after(() => setChangeSetReviewRunnerForTests()); const first = scheduleChangeSetReview(dir, set.id, "client-spoof-attempt"); const duplicate = scheduleChangeSetReview(dir, set.id, "different-client"); assert.equal(first.id, duplicate.id); const completed = await settle(dir, set.id); assert.equal(completed?.status, "completed"); assert.equal(completed?.reviewer.profile, "change_set_reviewer"); assert.notEqual(completed?.reviewer.id, "client-spoof-attempt"); assert.equal(hasCompletedChangeSetReview(dir, set.id, changeSetReviewRevision(set)), true); assert.equal(preflightChangeSetDecision(dir, set, "apply").applicable, true); });

test("a review of identical patch bytes cannot authorize a recapture with changed evidence", async (t) => { const dir = repository(t); const wt = createManagedWorktree(dir, { name: "review-recapture", ownerId: "writer" }); fs.writeFileSync(path.join(wt.path, "a.txt"), "same bytes\n"); git(wt.path, ["add", "a.txt"]); git(wt.path, ["commit", "-m", "same"]); const first = captureChangeSet(dir, wt.id, { command: "test", passed: true }); setChangeSetReviewRunnerForTests(async () => []); t.after(() => setChangeSetReviewRunnerForTests()); scheduleChangeSetReview(dir, first.id, "operator"); await settle(dir, first.id); const second = captureChangeSet(dir, wt.id, { command: "test", passed: true, rerun: 2 }); assert.equal(first.patchSha256, second.patchSha256); assert.notEqual(changeSetReviewRevision(first), changeSetReviewRevision(second)); assert.equal(hasCompletedChangeSetReview(dir, second.id, changeSetReviewRevision(second)), false); assert.equal(preflightChangeSetDecision(dir, second, "apply").blockingFindings?.some((item) => item.id === "change-set-independent-review"), true); });

test("only an independent reverify of a new immutable fix revision can unlock a fixed finding", async (t) => { const dir = repository(t); const wt = createManagedWorktree(dir, { name: "review", ownerId: "writer" }); fs.writeFileSync(path.join(wt.path, "a.txt"), "reviewed\n"); git(wt.path, ["add", "a.txt"]); git(wt.path, ["commit", "-m", "change"]); const original = captureChangeSet(dir, wt.id, { ok: true }); setChangeSetReviewRunnerForTests(async (input) => input.changeSet.id === original.id ? [{ severity: "error", path: "a.txt", line: 1, message: "broken", evidence: ["line evidence"] }] : []); t.after(() => setChangeSetReviewRunnerForTests()); await settle(dir, scheduleChangeSetReview(dir, original.id, "operator").changeSetId); const finding = new ReviewFindingStore(dir).list()[0]; assert(finding); const fixWorktree = createManagedWorktree(dir, { name: "fix", ownerId: "writer" }); fs.writeFileSync(path.join(fixWorktree.path, "a.txt"), "fixed\n"); git(fixWorktree.path, ["add", "a.txt"]); git(fixWorktree.path, ["commit", "-m", "fix"]); const fix = captureChangeSet(dir, fixWorktree.id, { ok: true }); const store = new ReviewFindingStore(dir); store.transition(finding.id, "accepted", { id: "writer" }); const accepted = store.list({ changeSetId: original.id })[0]; store.transition(finding.id, "fixed", { id: "writer" }, { expectedVersion: accepted.version, fixRef: fix.id }); assert.throws(() => store.transition(finding.id, "verified", { id: "other" }, { evidence: ["spoof"] }), /reserved/i); assert.throws(() => scheduleChangeSetReview(dir, original.id, "operator", "reverify"), /new immutable revision/i); await settle(dir, scheduleChangeSetReview(dir, fix.id, "operator").changeSetId); const reverify = scheduleChangeSetReview(dir, fix.id, "operator", "reverify"); const done = await settle(dir, fix.id); assert.equal(done?.id, reverify.id); assert.equal(done?.verificationResults?.[0]?.status, "verified"); assert.equal(new ReviewFindingStore(dir).list({ changeSetId: original.id })[0].lifecycle, "verified"); applyChangeSetDecision(dir, original, "reject"); removeManagedWorktree(dir, wt.id); assert.equal(preflightChangeSetDecision(dir, fix, "apply").applicable, true); });

test("concurrent run finalization merges records by run id without clobbering", async (t) => { const dir = repository(t); const first = createManagedWorktree(dir, { name: "one" }); const second = createManagedWorktree(dir, { name: "two" }); fs.writeFileSync(path.join(first.path, "a.txt"), "one\n"); git(first.path, ["add", "a.txt"]); git(first.path, ["commit", "-m", "one"]); fs.writeFileSync(path.join(second.path, "a.txt"), "two\n"); git(second.path, ["add", "a.txt"]); git(second.path, ["commit", "-m", "two"]); const a = captureChangeSet(dir, first.id, { ok: true }); const b = captureChangeSet(dir, second.id, { ok: true }); setChangeSetReviewRunnerForTests(async () => { await new Promise(resolve => setTimeout(resolve, 20)); return []; }); t.after(() => setChangeSetReviewRunnerForTests()); const ra = scheduleChangeSetReview(dir, a.id, "operator"); const rb = scheduleChangeSetReview(dir, b.id, "operator"); await settle(dir, ra.changeSetId); await settle(dir, rb.changeSetId); const runs = listChangeSetReviewRuns(dir); assert.equal(runs.find(run => run.id === ra.id)?.status, "completed"); assert.equal(runs.find(run => run.id === rb.id)?.status, "completed"); });

test("restart reconciliation preserves terminals and resumes queued and stale running leases once", async (t) => { const dir = repository(t); const wt = createManagedWorktree(dir, { name: "restart" }); fs.writeFileSync(path.join(wt.path, "a.txt"), "restart\n"); git(wt.path, ["add", "a.txt"]); git(wt.path, ["commit", "-m", "restart"]); const set = captureChangeSet(dir, wt.id, { ok: true }); setChangeSetReviewRunnerForTests(async () => []); t.after(() => setChangeSetReviewRunnerForTests()); const terminal = scheduleChangeSetReview(dir, set.id, "operator"); await settle(dir, set.id); const file = path.join(dir, ".history", "change-set-review-runs.json"); const runs = JSON.parse(fs.readFileSync(file, "utf8")) as Array<Record<string, unknown>>; const completed = { ...runs.find(item => item.id === terminal.id)! }; const expired = Date.now() - 120_000; const queued = { ...completed, id: "orphan-queued", attempt: 2, status: "queued", completedAt: undefined, startedAt: undefined, ownerPid: 2_147_483_647, ownerToken: "dead-queued", heartbeatAt: expired, leaseExpiresAt: expired, findingIds: [] }; const running = { ...completed, id: "orphan-running", attempt: 3, status: "running", completedAt: undefined, startedAt: new Date(expired).toISOString(), ownerPid: 2_147_483_647, ownerToken: "dead-running", heartbeatAt: expired, leaseExpiresAt: expired, findingIds: [] }; fs.writeFileSync(file, JSON.stringify([completed, queued, running], null, 2) + "\n"); const initial = reconcileChangeSetReviewRuns(dir); assert.equal(initial.find(item => item.id === terminal.id)?.status, "completed"); assert.equal(initial.find(item => item.id === "orphan-running")?.status, "interrupted"); assert.equal(initial.filter(item => item.retryOf === "orphan-running").length, 1); for (let i = 0; i < 150; i += 1) { const current = listChangeSetReviewRuns(dir); if (current.find(item => item.id === "orphan-queued")?.status === "completed" && current.find(item => item.retryOf === "orphan-running")?.status === "completed") break; await new Promise(resolve => setTimeout(resolve, 10)); } const final = listChangeSetReviewRuns(dir); assert.equal(final.find(item => item.id === terminal.id)?.status, "completed"); assert.equal(final.find(item => item.id === "orphan-running")?.status, "interrupted"); assert.equal(final.find(item => item.id === "orphan-queued")?.status, "completed"); assert.equal(final.filter(item => item.retryOf === "orphan-running").length, 1); assert.equal(final.find(item => item.retryOf === "orphan-running")?.status, "completed"); });

test("workspace session startup reconciles review runs without a list request", async (t) => { const dir = repository(t); const wt = createManagedWorktree(dir, { name: "startup" }); fs.writeFileSync(path.join(wt.path, "a.txt"), "startup\n"); git(wt.path, ["add", "a.txt"]); git(wt.path, ["commit", "-m", "startup"]); const set = captureChangeSet(dir, wt.id, { ok: true }); setChangeSetReviewRunnerForTests(async () => []); t.after(() => setChangeSetReviewRunnerForTests()); const original = scheduleChangeSetReview(dir, set.id, "operator"); await settle(dir, set.id); const runPath = path.join(dir, ".history", "change-set-review-runs.json"); const runs = JSON.parse(fs.readFileSync(runPath, "utf8")) as Array<Record<string, unknown>>; const expired = Date.now() - 120_000; runs.push({ ...runs[0], id: "startup-orphan", attempt: 2, status: "queued", startedAt: undefined, completedAt: undefined, ownerPid: 2_147_483_647, ownerToken: "dead-startup", heartbeatAt: expired, leaseExpiresAt: expired, findingIds: [] }); fs.writeFileSync(runPath, JSON.stringify(runs, null, 2) + "\n"); const configPath = path.join(path.dirname(dir), `users-${original.id}.json`); fs.writeFileSync(configPath, JSON.stringify({ allowedRoots: [dir], users: [{ username: "reviewer", password: "secret", defaultWorkspace: dir, isAdmin: true }] })); t.after(() => fs.rmSync(configPath, { force: true })); const manager = new SessionManager(configPath); assert(manager.login("reviewer", "secret")); for (let i = 0; i < 150; i += 1) { const persisted = JSON.parse(fs.readFileSync(runPath, "utf8")) as Array<{ id: string; status: string }>; if (persisted.find(item => item.id === "startup-orphan")?.status === "completed") return; await new Promise(resolve => setTimeout(resolve, 10)); } assert.fail("startup reconciliation did not resume orphaned review run"); });
