import React, { useEffect, useMemo, useState } from "react";
import { Gauge, RefreshCw, Save, ShieldAlert } from "lucide-react";
import { useI18n } from "../i18n";
import { useModelGovernance } from "../hooks/useModelGovernance";
import type { ModelBudgetEntry } from "../types";

interface Props { token: string; visible: boolean; modelName: string; workspaceId: string; readOnly: boolean; onShowToast: (message: string) => void; }
export const ModelGovernancePanel: React.FC<Props> = ({ token, visible, modelName, workspaceId, readOnly, onShowToast }) => {
  const { t } = useI18n(); const governance = useModelGovernance(token, visible, modelName); const [draft, setDraft] = useState({ maxTokens: "", maxCostUsd: "", warningRatio: "0.8" }); const [estimate, setEstimate] = useState({ tokens: "", cost: "" }); const [warning, setWarning] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const workspaceBudget = useMemo(() => governance.budgets.find((entry) => entry.scope.kind === "workspace" && entry.scope.id === workspaceId) || ({ scope: { kind: "workspace", id: workspaceId }, version: 0, policy: {}, usedTokens: 0, usedCostUsd: 0, updatedAt: 0 } as ModelBudgetEntry), [governance.budgets, workspaceId]);
  useEffect(() => setDraft({ maxTokens: workspaceBudget.policy.maxTokens?.toString() || "", maxCostUsd: workspaceBudget.policy.maxCostUsd?.toString() || "", warningRatio: workspaceBudget.policy.warningRatio?.toString() || "0.8" }), [workspaceBudget]);
  const capability = governance.capability;
  return <section className="settings-card settings-card-full model-governance-card"><div className="settings-card-header"><div className="settings-card-title"><Gauge size={16}/><span>{t("governance.title")}</span></div><button className="settings-inline-btn" type="button" onClick={() => void governance.refresh(true)} disabled={governance.loading}><RefreshCw size={14}/>{t("common.refresh")}</button></div>
    {governance.error && <div className="settings-error-banner" role="alert">{governance.error}</div>}
    {capability && <><div className="governance-capability-head"><strong>{capability.providerId} · {capability.capabilities.modelName}</strong><span>{capability.adapters.join(", ")}</span></div><div className="governance-capability-grid">{Object.entries(capability.capabilities.supports || {}).map(([feature, supported]) => <span className={`settings-status-badge ${supported ? "enabled" : "disabled-state"}`} key={feature}>{feature}: {supported ? t("governance.supported") : t("governance.unsupported")}</span>)}</div><div className="settings-help-text">{t("governance.fallbackGuard")}</div><div className="governance-suitability-grid">{Object.entries(capability.suitability).map(([role, suitability]) => <div className={suitability.suitable ? "suitable" : "unsuitable"} key={role}><strong>{role}</strong><span>{suitability.suitable ? t("governance.suitable") : t("governance.missing", { features: suitability.missing.join(", ") })}</span></div>)}</div></>}
    <div className="governance-budget"><div><strong>{t("governance.workspaceBudget")}</strong><span>{t("governance.usage", { tokens: workspaceBudget.usedTokens, cost: workspaceBudget.usedCostUsd })}</span>{workspaceBudget.lastUsage && <small>{workspaceBudget.lastUsage.provenance.source === "provider_reported" ? t("governance.reportedUsage") : t("governance.estimatedUsage")} · {workspaceBudget.lastUsage.provenance.providerId}/{workspaceBudget.lastUsage.provenance.modelName}</small>}</div>{!readOnly && <div className="governance-budget-form">{(["maxTokens", "maxCostUsd", "warningRatio"] as const).map((field) => <label key={field}>{t(`governance.${field}`)}<input type="number" min="0" step={field === "maxTokens" ? 1 : 0.01} value={draft[field]} onChange={(event) => setDraft((current) => ({ ...current, [field]: event.target.value }))}/></label>)}<button type="button" disabled={saving} onClick={() => { setSaving(true); const policy = { ...(draft.maxTokens ? { maxTokens: Number(draft.maxTokens) } : {}), ...(draft.maxCostUsd ? { maxCostUsd: Number(draft.maxCostUsd) } : {}), ...(draft.warningRatio ? { warningRatio: Number(draft.warningRatio) } : {}) }; void governance.updateBudget(workspaceBudget, policy).then(() => onShowToast(t("governance.budgetSaved"))).catch((reason) => onShowToast(reason instanceof Error ? reason.message : t("governance.budgetFailed"))).finally(() => setSaving(false)); }}><Save size={13}/>{t("common.save")}</button></div>}</div>
    <div className="governance-preflight"><strong>{t("governance.dispatchPreflight")}</strong><input type="number" min="0" placeholder={t("governance.estimatedTokens")} value={estimate.tokens} onChange={(event) => setEstimate((current) => ({ ...current, tokens: event.target.value }))}/><input type="number" min="0" step="0.01" placeholder={t("governance.estimatedCost")} value={estimate.cost} onChange={(event) => setEstimate((current) => ({ ...current, cost: event.target.value }))}/><button type="button" disabled={!estimate.tokens || !estimate.cost} onClick={() => void governance.preflight(Number(estimate.tokens), Number(estimate.cost)).then((result) => setWarning(result.preflight.warnings.length ? t("governance.nearBudget", { count: result.preflight.warnings.length }) : t("governance.withinBudget"))).catch((reason) => setWarning(reason instanceof Error ? reason.message : t("governance.budgetFailed")))}>{t("governance.checkDispatch")}</button>{warning && <div className="governance-dispatch-warning" role="status"><ShieldAlert size={14}/>{warning}</div>}</div>
  </section>;
};
