import crypto from "node:crypto";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { isProcessAlive } from "../utils/processLiveness.js";
import { redactSecrets } from "../agent/secretRedaction.js";
import { safePath } from "../utils/safePath.js";

export type CollaborationSubject = { kind: "human" | "agent"; id: string };
export type AnchorStatus = "active" | "relocated" | "stale";
export interface CollaborationAnchor { path: string; startLine: number; endLine: number; fileDigest: string; revision: string; selectedText?: string; contextBefore?: string; contextAfter?: string; status: AnchorStatus; }
export interface CollaborationClaim { id: string; subject: CollaborationSubject; anchor: CollaborationAnchor; createdAt: number; updatedAt: number; }
export interface CollaborationPresence { subject: CollaborationSubject; online: boolean; activePath?: string; cursorLine?: number; cursorColumn?: number; activity?: string; socketCount?: number; updatedAt: number; }
export interface CollaborationComment { id: string; author: CollaborationSubject; body: string; anchor: CollaborationAnchor; mentions: CollaborationSubject[]; evidenceLinks: string[]; createdAt: number; updatedAt: number; resolvedAt?: number; resolvedBy?: string; }
export interface CollaborationReviewRequest { id: string; createdBy: CollaborationSubject; assignees: CollaborationSubject[]; anchor: CollaborationAnchor; message?: string; status: "open" | "completed" | "stale"; commentIds: string[]; createdAt: number; updatedAt: number; }
export interface CollaborationBuffer { id: string; username: string; path: string; version: number; digest: string; savedDigest: string; baseDigest: string; revision: string; dirty: boolean; updatedAt: number; }
export type CollaborationMergeChoice = "apply-human" | "apply-agent" | "manual";
export type CollaborationMergeDecisionStatus = "resolution_pending" | "resolved" | "stale";
export interface CollaborationMergeAllowedAction { choice: CollaborationMergeChoice; enabled: boolean; requiresSave: boolean; requiresNewRevision: boolean; reason?: string; }
export interface CollaborationMergePreview { id: string; changeSetId: string; path: string; version: number; revision: string; baseDigest: string; humanDigest: string; upstreamDigest: string; agentDigest: string; humanBufferVersion?: number; allowedActions: CollaborationMergeAllowedAction[]; hunks: Array<{ id: string; base: string; human?: string; upstream: string; agent: string; conflict: boolean }>; createdBy: string; createdAt: number; updatedAt: number; }
export interface CollaborationMergeDecision { id: string; previewId: string; previewVersion: number; changeSetId: string; path: string; revision: string; baseDigest: string; humanDigest: string; upstreamDigest: string; agentDigest: string; humanBufferVersion?: number; choice: CollaborationMergeChoice; status: CollaborationMergeDecisionStatus; actorId: string; reason?: string; resolvedDigest?: string; supersedesDecisionId?: string; createdAt: number; }
export interface CollaborationActivity { id: string; type: "claim" | "presence" | "comment" | "review_request" | "mention" | "buffer" | "merge_preview" | "merge_decision" | "mutation"; actorId: string; createdAt: number; path?: string; targetId?: string; evidenceLinks?: string[]; detail?: string; }
export interface CollaborationState { schemaVersion: 1; version: number; claims: CollaborationClaim[]; presence: CollaborationPresence[]; comments: CollaborationComment[]; reviewRequests: CollaborationReviewRequest[]; buffers: CollaborationBuffer[]; mergePreviews: CollaborationMergePreview[]; mergeDecisions: CollaborationMergeDecision[]; activity: CollaborationActivity[]; }
export interface CollaborationConflict { code: "unsaved_human_buffer" | "saved_human_drift" | "upstream_drift"; path: string; changeSetId: string; revision: string; baseDigest: string; humanDigest: string; upstreamDigest: string; agentDigest: string; bufferVersion?: number; resolutionStatus?: CollaborationMergeDecisionStatus; allowedActions?: CollaborationMergeAllowedAction[]; resolvedByDecisionId?: string; }
export class CollaborationVersionConflictError extends Error { readonly code = "collaboration_version_conflict"; constructor(readonly expectedVersion: number, readonly actualVersion: number) { super(`Collaboration version conflict: expected ${expectedVersion}, got ${actualVersion}`); } }
export class CollaborationStoreCorruptionError extends Error {
  readonly code = "collaboration_store_corrupt";
  constructor(readonly storePath: string, reason: string, cause?: unknown) {
    super(`Collaboration store is corrupt or unreadable: ${reason}`, { cause });
    this.name = "CollaborationStoreCorruptionError";
  }
}

const EMPTY_DIGEST = crypto.createHash("sha256").update("").digest("hex");
const MAX_TEXT = 8_000;
function emptyState(): CollaborationState { return { schemaVersion: 1, version: 1, claims: [], presence: [], comments: [], reviewRequests: [], buffers: [], mergePreviews: [], mergeDecisions: [], activity: [] }; }
function digest(value: string | Buffer): string { return crypto.createHash("sha256").update(value).digest("hex"); }
function cleanId(value: unknown, label = "identifier"): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._:@-]{0,199}$/.test(value)) throw new Error(`Invalid ${label}`); return value; }
function cleanSubject(value: CollaborationSubject): CollaborationSubject { return { kind: value?.kind === "agent" ? "agent" : value?.kind === "human" ? "human" : (() => { throw new Error("Invalid collaboration subject"); })(), id: cleanId(value?.id, "subject id") }; }
function cleanRelative(value: unknown): string { if (typeof value !== "string") throw new Error("Invalid collaboration path"); const normalized = value.trim().replace(/\\/g, "/").replace(/^\.\//, ""); if (!normalized || path.posix.isAbsolute(normalized) || normalized.split("/").some((part) => !part || part === "." || part === "..") || [".git", ".history", ".team", ".checkpoints", ".codex", ".omx"].includes(normalized.split("/")[0])) throw new Error("Invalid collaboration path"); return normalized; }
function cleanDigest(value: unknown, label = "digest"): string { if (typeof value !== "string" || !/^[a-f0-9]{64}$/.test(value)) throw new Error(`Invalid ${label}`); return value; }
function stateFile(workspace: string): string { return path.join(path.resolve(workspace), ".team", "collaboration-v1.json"); }
function canonicalWorkspace(input: string): string { const workspace = path.resolve(input); const marker = path.join(workspace, ".git"); try { const stat = fs.lstatSync(marker); if (stat.isDirectory()) return workspace; if (stat.isFile()) { const match = fs.readFileSync(marker, "utf8").match(/^gitdir:\s*(.+)\s*$/m); if (match) { const gitDir = path.resolve(workspace, match[1]); const suffix = `${path.sep}.git${path.sep}worktrees${path.sep}`; const index = gitDir.indexOf(suffix); if (index > 0) return gitDir.slice(0, index); } } } catch { /* non-Git collaboration workspace */ } return workspace; }
function atomicWrite(file: string, value: unknown): void { fs.mkdirSync(path.dirname(file), { recursive: true }); const temporary = `${file}.${process.pid}.${crypto.randomUUID()}.tmp`; fs.writeFileSync(temporary, `${JSON.stringify(redactSecrets(value), null, 2)}\n`, { encoding: "utf8", flag: "wx", mode: 0o600 }); fs.renameSync(temporary, file); }
function readState(workspace: string): CollaborationState {
  const target = stateFile(workspace);
  let source: string;
  try {
    source = fs.readFileSync(target, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return emptyState();
    throw new CollaborationStoreCorruptionError(target, "persisted source cannot be read", error);
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(source);
  } catch (error) {
    throw new CollaborationStoreCorruptionError(target, "persisted source is not valid JSON", error);
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new CollaborationStoreCorruptionError(target, "persisted root must be an object");
  const value = parsed as Partial<CollaborationState>;
  if (value.schemaVersion !== 1) throw new CollaborationStoreCorruptionError(target, "unsupported schema version");
  if (!Number.isSafeInteger(value.version) || (value.version || 0) < 1) throw new CollaborationStoreCorruptionError(target, "invalid state version");
  const collectionKeys = ["claims", "presence", "comments", "reviewRequests", "buffers", "mergePreviews", "mergeDecisions", "activity"] as const;
  for (const key of collectionKeys) {
    if (value[key] !== undefined && !Array.isArray(value[key])) throw new CollaborationStoreCorruptionError(target, `invalid ${key} collection`);
  }
  const fallback = emptyState();
  return {
    ...fallback,
    ...value,
    claims: value.claims || [], presence: value.presence || [], comments: value.comments || [], reviewRequests: value.reviewRequests || [],
    buffers: value.buffers || [], mergePreviews: value.mergePreviews || [], mergeDecisions: value.mergeDecisions || [], activity: value.activity || [],
  } as CollaborationState;
}
const alive = isProcessAlive;
function withLock<T>(workspace: string, operation: (state: CollaborationState) => T): T { const file = stateFile(workspace); const lock = `${file}.lock`; fs.mkdirSync(path.dirname(lock), { recursive: true }); const token = crypto.randomUUID(); let fd: number | undefined; for (let attempt = 0; attempt < 400; attempt += 1) { try { fd = fs.openSync(lock, "wx", 0o600); fs.writeFileSync(fd, JSON.stringify({ token, pid: process.pid, createdAt: Date.now() })); break; } catch { try { const owner = JSON.parse(fs.readFileSync(lock, "utf8")) as { pid?: number; createdAt?: number }; if (owner.pid && !alive(owner.pid) && Date.now() - (owner.createdAt || 0) > 1_000) fs.rmSync(lock, { force: true }); } catch { /* malformed locks fail closed until stale */ } Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 5); } } if (fd === undefined) throw new Error("Collaboration store is busy"); try { const state = readState(workspace); const result = operation(state); atomicWrite(file, state); return result; } finally { fs.closeSync(fd); try { const owner = JSON.parse(fs.readFileSync(lock, "utf8")) as { token?: string }; if (owner.token === token) fs.rmSync(lock, { force: true }); } catch { /* already released */ } } }
function currentFile(workspace: string, relative: string): { content: string; digest: string } { const target = safePath(relative, path.resolve(workspace)); try { const stat = fs.lstatSync(target); if (!stat.isFile() || stat.isSymbolicLink() || stat.size > 2 * 1024 * 1024) throw new Error("Collaboration target must be a bounded regular file"); const content = fs.readFileSync(target, "utf8"); return { content, digest: digest(content) }; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { content: "", digest: EMPTY_DIGEST }; throw error; } }
function gitText(workspace: string, revision: string, relative: string): string { try { return execFileSync("git", ["-C", workspace, "show", `${revision}:${relative}`], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }); } catch { return ""; } }
function activity(state: CollaborationState, type: CollaborationActivity["type"], actorId: string, input: Partial<CollaborationActivity> = {}): void { state.activity = [{ id: crypto.randomUUID(), type, actorId, createdAt: Date.now(), ...input }, ...state.activity].slice(0, 500); }
function mentions(body: string, humanIds: string[] = [], agentIds: string[] = []): CollaborationSubject[] { const result: CollaborationSubject[] = []; for (const match of body.matchAll(/@([A-Za-z0-9_.-]{1,160})/g)) { const id = match[1]; const kind = agentIds.includes(id) || id.startsWith("agent-") || id.startsWith("teammate:") ? "agent" : "human"; if (!humanIds.length && !agentIds.length || humanIds.includes(id) || agentIds.includes(id) || kind === "agent") result.push({ kind, id }); } return [...new Map(result.map((item) => [`${item.kind}:${item.id}`, item])).values()]; }
function allowedActions(dirty: boolean): CollaborationMergeAllowedAction[] { return [
  { choice: "apply-agent", enabled: true, requiresSave: false, requiresNewRevision: false },
  { choice: "apply-human", enabled: true, requiresSave: dirty, requiresNewRevision: true, reason: dirty ? "Save the human buffer, then bind a new ChangeSet revision that preserves its digest" : "Bind a new ChangeSet revision that preserves the saved human digest" },
  { choice: "manual", enabled: true, requiresSave: true, requiresNewRevision: true, reason: "Save the explicit manual resolution, then bind a new ChangeSet revision that preserves its digest" },
]; }

export class CollaborationStore {
  readonly workspace: string;
  constructor(workspace: string) { this.workspace = canonicalWorkspace(workspace); }
  private revision(): string { try { return execFileSync("git", ["-C", this.workspace, "rev-parse", "HEAD"], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim(); } catch { return "workspace"; } }
  private anchor(input: { path: string; startLine?: number; endLine?: number; selectedText?: string; contextBefore?: string; contextAfter?: string; revision?: string }): CollaborationAnchor { const relative = cleanRelative(input.path); const file = currentFile(this.workspace, relative); const startLine = Number.isSafeInteger(input.startLine) && (input.startLine || 0) > 0 ? input.startLine! : 1; const endLine = Number.isSafeInteger(input.endLine) && input.endLine! >= startLine ? input.endLine! : startLine; return { path: relative, startLine, endLine, fileDigest: file.digest, revision: (input.revision || this.revision()).slice(0, 160), ...(input.selectedText?.trim() ? { selectedText: input.selectedText.slice(0, MAX_TEXT) } : {}), ...(input.contextBefore ? { contextBefore: input.contextBefore.slice(0, 1_000) } : {}), ...(input.contextAfter ? { contextAfter: input.contextAfter.slice(0, 1_000) } : {}), status: "active" }; }
  private relocate(anchor: CollaborationAnchor): boolean { const file = currentFile(this.workspace, anchor.path); if (file.digest === anchor.fileDigest) return false; if (anchor.selectedText) { const first = file.content.indexOf(anchor.selectedText); if (first >= 0 && first === file.content.lastIndexOf(anchor.selectedText)) { const line = file.content.slice(0, first).split("\n").length; anchor.startLine = line; anchor.endLine = line + anchor.selectedText.split("\n").length - 1; anchor.fileDigest = file.digest; anchor.revision = this.revision(); anchor.status = "relocated"; return true; } } anchor.status = "stale"; return true; }
  snapshot(): CollaborationState { return withLock(this.workspace, (state) => { let changed = false; for (const item of [...state.claims, ...state.comments, ...state.reviewRequests]) changed = this.relocate(item.anchor) || changed; const now = Date.now(); for (const item of state.presence) if (item.online && now - item.updatedAt > 90_000) { item.online = false; item.socketCount = 0; changed = true; } for (const preview of state.mergePreviews) { const buffer = [...state.buffers].filter((item) => item.path === preview.path && item.dirty).sort((a, b) => b.updatedAt - a.updatedAt)[0]; const next = allowedActions(Boolean(buffer)); if (!preview.allowedActions || JSON.stringify(preview.allowedActions) !== JSON.stringify(next)) { preview.allowedActions = next; changed = true; } } for (const decision of state.mergeDecisions) { if (!decision.status) { decision.status = decision.choice === "apply-agent" ? "resolved" : "resolution_pending"; changed = true; } if (decision.status === "stale") continue; const current = currentFile(this.workspace, decision.path); const buffer = [...state.buffers].filter((item) => item.path === decision.path && item.dirty).sort((a, b) => b.updatedAt - a.updatedAt)[0]; const newerRevision = state.mergePreviews.some((item) => item.path === decision.path && item.revision !== decision.revision && item.createdAt > decision.createdAt); const bufferChanged = decision.humanBufferVersion === undefined ? Boolean(buffer) : !buffer || buffer.version !== decision.humanBufferVersion || buffer.digest !== decision.humanDigest; if (current.digest !== decision.upstreamDigest || bufferChanged || newerRevision) { decision.status = "stale"; changed = true; } } if (changed) { state.version += 1; } return structuredClone(state); }); }
  upsertClaim(input: { subject: CollaborationSubject; path: string; claimed: boolean; startLine?: number; endLine?: number; selectedText?: string; contextBefore?: string; contextAfter?: string }, expectedVersion: number): CollaborationState { return withLock(this.workspace, (state) => { if (state.version !== expectedVersion) throw new CollaborationVersionConflictError(expectedVersion, state.version); const subject = cleanSubject(input.subject); const anchor = this.anchor(input); const overlaps = (claim: CollaborationClaim) => claim.anchor.path === anchor.path && claim.subject.id !== subject.id && claim.anchor.status !== "stale" && !(claim.anchor.endLine < anchor.startLine || claim.anchor.startLine > anchor.endLine); if (input.claimed && state.claims.some(overlaps)) throw new Error("File range is already claimed"); state.claims = state.claims.filter((claim) => !(claim.anchor.path === anchor.path && claim.subject.kind === subject.kind && claim.subject.id === subject.id)); if (input.claimed) state.claims.push({ id: crypto.randomUUID(), subject, anchor, createdAt: Date.now(), updatedAt: Date.now() }); state.version += 1; activity(state, "claim", subject.id, { path: anchor.path, detail: input.claimed ? "claimed" : "released" }); return structuredClone(state); }); }
  upsertPresence(input: { subject: CollaborationSubject; online: boolean; activePath?: string; cursorLine?: number; cursorColumn?: number; activity?: string; socketDelta?: number }): CollaborationState { return withLock(this.workspace, (state) => { const subject = cleanSubject(input.subject); const existing = state.presence.find((item) => item.subject.kind === subject.kind && item.subject.id === subject.id); const socketCount = Math.max(0, (existing?.socketCount || 0) + (input.socketDelta || 0)); const item: CollaborationPresence = { subject, online: input.socketDelta === undefined ? input.online : socketCount > 0, ...(input.activePath ? { activePath: cleanRelative(input.activePath) } : existing?.activePath ? { activePath: existing.activePath } : {}), ...(Number.isSafeInteger(input.cursorLine) ? { cursorLine: input.cursorLine } : existing?.cursorLine ? { cursorLine: existing.cursorLine } : {}), ...(Number.isSafeInteger(input.cursorColumn) ? { cursorColumn: input.cursorColumn } : existing?.cursorColumn ? { cursorColumn: existing.cursorColumn } : {}), ...(input.activity?.trim() ? { activity: input.activity.slice(0, 500) } : existing?.activity ? { activity: existing.activity } : {}), socketCount, updatedAt: Date.now() }; state.presence = [...state.presence.filter((entry) => !(entry.subject.kind === subject.kind && entry.subject.id === subject.id)), item]; state.version += 1; activity(state, "presence", subject.id, { path: item.activePath, detail: item.online ? "online" : "offline" }); return structuredClone(state); }); }
  addComment(input: { author: CollaborationSubject; body: string; path: string; startLine?: number; endLine?: number; selectedText?: string; contextBefore?: string; contextAfter?: string; evidenceLinks?: string[]; humanIds?: string[]; agentIds?: string[] }, expectedVersion: number): CollaborationComment { return withLock(this.workspace, (state) => { if (state.version !== expectedVersion) throw new CollaborationVersionConflictError(expectedVersion, state.version); const author = cleanSubject(input.author); const body = redactSecrets(input.body || "").trim().slice(0, MAX_TEXT); if (!body) throw new Error("Comment body is required"); const foundMentions = mentions(body, input.humanIds, input.agentIds); const evidenceLinks = (input.evidenceLinks || []).filter((item) => typeof item === "string" && item.trim()).map((item) => item.slice(0, 500)).slice(0, 30); const comment: CollaborationComment = { id: crypto.randomUUID(), author, body, anchor: this.anchor(input), mentions: foundMentions, evidenceLinks, createdAt: Date.now(), updatedAt: Date.now() }; state.comments.push(comment); state.version += 1; activity(state, "comment", author.id, { path: comment.anchor.path, targetId: comment.id, evidenceLinks }); for (const mention of foundMentions) activity(state, "mention", author.id, { path: comment.anchor.path, targetId: `${mention.kind}:${mention.id}`, detail: comment.id }); return structuredClone(comment); }); }
  createReviewRequest(input: { createdBy: CollaborationSubject; assignees: CollaborationSubject[]; path: string; startLine?: number; endLine?: number; selectedText?: string; contextBefore?: string; contextAfter?: string; message?: string }, expectedVersion: number): CollaborationReviewRequest { return withLock(this.workspace, (state) => { if (state.version !== expectedVersion) throw new CollaborationVersionConflictError(expectedVersion, state.version); const createdBy = cleanSubject(input.createdBy); const assignees = [...new Map((input.assignees || []).map(cleanSubject).map((item) => [`${item.kind}:${item.id}`, item])).values()]; if (!assignees.length) throw new Error("At least one human or agent assignee is required"); const request: CollaborationReviewRequest = { id: crypto.randomUUID(), createdBy, assignees, anchor: this.anchor(input), ...(input.message?.trim() ? { message: redactSecrets(input.message).slice(0, 4_000) } : {}), status: "open", commentIds: [], createdAt: Date.now(), updatedAt: Date.now() }; state.reviewRequests.push(request); state.version += 1; activity(state, "review_request", createdBy.id, { path: request.anchor.path, targetId: request.id }); return structuredClone(request); }); }
  registerBuffer(input: { username: string; path: string; version: number; digest: string; savedDigest: string; baseDigest?: string; revision: string }): CollaborationBuffer { return withLock(this.workspace, (state) => { const username = cleanId(input.username, "username"); const relative = cleanRelative(input.path); if (!Number.isSafeInteger(input.version) || input.version < 0) throw new Error("Invalid buffer version"); const current = currentFile(this.workspace, relative); const prior = state.buffers.find((item) => item.username === username && item.path === relative); if (prior && input.version <= prior.version && input.digest !== prior.digest) throw new CollaborationVersionConflictError(input.version, prior.version); const buffer: CollaborationBuffer = { id: prior?.id || crypto.randomUUID(), username, path: relative, version: input.version, digest: cleanDigest(input.digest, "buffer digest"), savedDigest: cleanDigest(input.savedDigest, "saved digest"), baseDigest: input.baseDigest ? cleanDigest(input.baseDigest, "base digest") : prior?.baseDigest || current.digest, revision: cleanId(input.revision, "buffer revision"), dirty: input.digest !== input.savedDigest, updatedAt: Date.now() }; state.buffers = [...state.buffers.filter((item) => !(item.username === username && item.path === relative)), buffer]; state.version += 1; activity(state, "buffer", username, { path: relative, targetId: buffer.id, detail: buffer.dirty ? "unsaved" : "saved" }); return structuredClone(buffer); }); }
  closeBuffer(usernameInput: string, pathInput: string, expectedBufferVersion: number): CollaborationState { return withLock(this.workspace, (state) => { const username = cleanId(usernameInput, "username"); const relative = cleanRelative(pathInput); const item = state.buffers.find((buffer) => buffer.username === username && buffer.path === relative); if (!item) return structuredClone(state); if (item.version !== expectedBufferVersion) throw new CollaborationVersionConflictError(expectedBufferVersion, item.version); state.buffers = state.buffers.filter((buffer) => buffer !== item); state.version += 1; activity(state, "buffer", username, { path: relative, targetId: item.id, detail: "closed" }); return structuredClone(state); }); }
  recordMutation(pathInput: string, actorId = "system"): CollaborationState { return withLock(this.workspace, (state) => { const relative = cleanRelative(pathInput); let changed = false; for (const item of [...state.claims, ...state.comments, ...state.reviewRequests]) if (item.anchor.path === relative) changed = this.relocate(item.anchor) || changed; state.version += 1; activity(state, "mutation", actorId, { path: relative, detail: changed ? "anchors reconciled" : "content changed" }); return structuredClone(state); }); }
  recordMergePreview(input: Omit<CollaborationMergePreview, "id" | "version" | "allowedActions" | "createdAt" | "updatedAt">): CollaborationMergePreview { return withLock(this.workspace, (state) => { const buffer = [...state.buffers].filter((item) => item.path === input.path && item.dirty).sort((a, b) => b.updatedAt - a.updatedAt)[0]; const preview: CollaborationMergePreview = { ...input, changeSetId: cleanId(input.changeSetId, "change set id"), path: cleanRelative(input.path), revision: cleanDigest(input.revision, "change set revision"), baseDigest: cleanDigest(input.baseDigest), humanDigest: cleanDigest(input.humanDigest), upstreamDigest: cleanDigest(input.upstreamDigest), agentDigest: cleanDigest(input.agentDigest), ...(buffer ? { humanBufferVersion: buffer.version } : {}), allowedActions: allowedActions(Boolean(buffer)), id: crypto.randomUUID(), version: 1, createdAt: Date.now(), updatedAt: Date.now() }; state.mergePreviews.push(preview); state.mergePreviews = state.mergePreviews.slice(-200); state.version += 1; activity(state, "merge_preview", input.createdBy, { path: preview.path, targetId: preview.id }); return structuredClone(preview); }); }
  decideMerge(input: { previewId: string; expectedPreviewVersion: number; actorId: string; choice: CollaborationMergeChoice; revision: string; baseDigest: string; humanDigest: string; upstreamDigest: string; agentDigest: string; reason?: string; resolvedDigest?: string; supersedesDecisionId?: string }): CollaborationMergeDecision { return withLock(this.workspace, (state) => {
    const preview = state.mergePreviews.find((item) => item.id === cleanId(input.previewId, "preview id"));
    if (!preview) throw new Error("Merge preview not found");
    if (preview.version !== input.expectedPreviewVersion) throw new CollaborationVersionConflictError(input.expectedPreviewVersion, preview.version);
    if (!["apply-human", "apply-agent", "manual"].includes(input.choice)) throw new Error("Invalid merge choice");
    for (const key of ["revision", "baseDigest", "humanDigest", "upstreamDigest", "agentDigest"] as const) if (cleanDigest(input[key], key) !== preview[key]) throw new Error("Merge decision is stale for the exact digests/revision");
    const current = currentFile(this.workspace, preview.path);
    const buffer = [...state.buffers].filter((item) => item.path === preview.path && item.dirty).sort((a, b) => b.updatedAt - a.updatedAt)[0];
    if (current.digest !== preview.upstreamDigest || (preview.humanBufferVersion === undefined ? Boolean(buffer) : !buffer || buffer.version !== preview.humanBufferVersion || buffer.digest !== preview.humanDigest)) throw new Error("Merge decision is stale for the current buffer/workspace state");
    const resolvedDigest = input.resolvedDigest ? cleanDigest(input.resolvedDigest, "resolved digest") : undefined;
    if (input.choice === "manual" && !resolvedDigest) throw new Error("Manual merge requires a resolved digest");
    let status: CollaborationMergeDecisionStatus = input.choice === "apply-agent" ? "resolved" : "resolution_pending";
    let supersedesDecisionId: string | undefined;
    if (input.supersedesDecisionId) {
      const prior = state.mergeDecisions.find((item) => item.id === cleanId(input.supersedesDecisionId, "superseded decision id"));
      if (!prior || prior.path !== preview.path || prior.choice !== input.choice || prior.status === "resolved") throw new Error("Pending merge decision cannot be safely superseded");
      const targetDigest = input.choice === "apply-human" ? prior.humanDigest : prior.resolvedDigest;
      if (!targetDigest || buffer || preview.revision === prior.revision || current.digest !== targetDigest || preview.humanDigest !== targetDigest || preview.upstreamDigest !== targetDigest || preview.agentDigest !== targetDigest) throw new Error("Resolution still requires a saved human result and a new ChangeSet revision preserving that exact digest");
      status = "resolved";
      supersedesDecisionId = prior.id;
      prior.status = "stale";
    }
    const decision: CollaborationMergeDecision = { id: crypto.randomUUID(), previewId: preview.id, previewVersion: preview.version, changeSetId: preview.changeSetId, path: preview.path, revision: preview.revision, baseDigest: preview.baseDigest, humanDigest: preview.humanDigest, upstreamDigest: preview.upstreamDigest, agentDigest: preview.agentDigest, ...(preview.humanBufferVersion !== undefined ? { humanBufferVersion: preview.humanBufferVersion } : {}), choice: input.choice, status, actorId: cleanId(input.actorId, "actor id"), ...(input.reason?.trim() ? { reason: redactSecrets(input.reason).slice(0, 2_000) } : {}), ...(resolvedDigest ? { resolvedDigest } : {}), ...(supersedesDecisionId ? { supersedesDecisionId } : {}), createdAt: Date.now() };
    state.mergeDecisions.push(decision); state.mergeDecisions = state.mergeDecisions.slice(-500); state.version += 1; activity(state, "merge_decision", decision.actorId, { path: decision.path, targetId: decision.id, detail: `${decision.choice}:${decision.status}` }); return structuredClone(decision);
  }); }
  integrationAssessment(input: { id: string; patchSha256: string; baseSha: string; changedFiles: string[]; agentDigests?: Record<string, string> }): { conflicts: CollaborationConflict[]; resolved: CollaborationConflict[] } { const state = this.snapshot(); const conflicts: CollaborationConflict[] = []; const resolved: CollaborationConflict[] = []; for (const rawPath of input.changedFiles) { const relative = cleanRelative(rawPath); const upstream = currentFile(this.workspace, relative); const baseDigest = digest(gitText(this.workspace, input.baseSha, relative)); const agentDigest = input.agentDigests?.[relative] && /^[a-f0-9]{64}$/.test(input.agentDigests[relative]) ? input.agentDigests[relative] : input.patchSha256; const buffers = state.buffers.filter((item) => item.path === relative && item.dirty); const candidates: CollaborationConflict[] = buffers.map((buffer) => ({ code: "unsaved_human_buffer", path: relative, changeSetId: input.id, revision: input.patchSha256, baseDigest, humanDigest: buffer.digest, upstreamDigest: upstream.digest, agentDigest, bufferVersion: buffer.version })); if (!buffers.length && upstream.digest !== baseDigest) candidates.push({ code: gitText(this.workspace, "HEAD", relative) === upstream.content ? "upstream_drift" : "saved_human_drift", path: relative, changeSetId: input.id, revision: input.patchSha256, baseDigest, humanDigest: upstream.digest, upstreamDigest: upstream.digest, agentDigest }); for (const conflict of candidates) { const decisions = [...state.mergeDecisions].reverse().filter((item) => item.changeSetId === input.id && item.path === relative); const decision = decisions.find((item) => item.revision === conflict.revision && item.baseDigest === conflict.baseDigest && item.humanDigest === conflict.humanDigest && item.upstreamDigest === conflict.upstreamDigest && item.agentDigest === conflict.agentDigest && item.humanBufferVersion === conflict.bufferVersion); if (decision?.status === "resolved") resolved.push({ ...conflict, resolutionStatus: "resolved", resolvedByDecisionId: decision.id }); else conflicts.push({ ...conflict, resolutionStatus: decision?.status || (decisions.some((item) => item.status === "stale") ? "stale" : "resolution_pending"), allowedActions: allowedActions(Boolean(buffers.length)) }); } } return { conflicts, resolved }; }
  integrationConflicts(input: { id: string; patchSha256: string; baseSha: string; changedFiles: string[]; agentDigests?: Record<string, string> }): CollaborationConflict[] { return this.integrationAssessment(input).conflicts; }
  fileDigests(pathInput: string, baseRevision: string, agentContent?: string): { base: string; human: string; upstream: string; agent: string; humanBuffer?: CollaborationBuffer } { const relative = cleanRelative(pathInput); const current = currentFile(this.workspace, relative); const buffer = [...this.snapshot().buffers].filter((item) => item.path === relative && item.dirty).sort((a, b) => b.updatedAt - a.updatedAt)[0]; return { base: digest(gitText(this.workspace, baseRevision, relative)), human: buffer?.digest || current.digest, upstream: current.digest, agent: agentContent === undefined ? current.digest : digest(agentContent), ...(buffer ? { humanBuffer: buffer } : {}) }; }
}

export { digest as collaborationDigest };
