import * as monaco from "monaco-editor";

export const EDITOR_THEME_NAME = "offline-ai-light";

export function registerEditorTheme(): void {
  monaco.editor.defineTheme(EDITOR_THEME_NAME, {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "7C8596", fontStyle: "italic" },
      { token: "keyword", foreground: "0F5CC0", fontStyle: "bold" },
      { token: "operator", foreground: "46556F" },
      { token: "string", foreground: "0F766E" },
      { token: "string.escape", foreground: "2563EB" },
      { token: "number", foreground: "A16207" },
      { token: "regexp", foreground: "7C3AED" },
      { token: "type", foreground: "0E7490" },
      { token: "type.identifier", foreground: "0E7490" },
      { token: "typeParameter", foreground: "0E7490" },
      { token: "delimiter", foreground: "667085" },
      { token: "delimiter.bracket", foreground: "475467" },
      { token: "predefined", foreground: "C2410C" },
      { token: "namespace", foreground: "7C3AED" },
      { token: "namespace.defaultLibrary", foreground: "7C3AED", fontStyle: "italic" },
      { token: "class", foreground: "0E7490", fontStyle: "bold" },
      { token: "class.declaration", foreground: "0E7490", fontStyle: "bold" },
      { token: "class.defaultLibrary", foreground: "0E7490", fontStyle: "bold italic" },
      { token: "interface", foreground: "0E7490", fontStyle: "bold" },
      { token: "interface.declaration", foreground: "0E7490", fontStyle: "bold" },
      { token: "enum", foreground: "0E7490", fontStyle: "bold" },
      { token: "enum.declaration", foreground: "0E7490", fontStyle: "bold" },
      { token: "type.declaration", foreground: "0E7490", fontStyle: "bold" },
      { token: "type.defaultLibrary", foreground: "0E7490", fontStyle: "italic" },
      { token: "typeParameter.declaration", foreground: "0E7490", fontStyle: "italic" },
      { token: "function", foreground: "B45309" },
      { token: "function.declaration", foreground: "B45309", fontStyle: "bold" },
      { token: "function.defaultLibrary", foreground: "B45309", fontStyle: "italic" },
      { token: "method", foreground: "B45309" },
      { token: "method.declaration", foreground: "B45309", fontStyle: "bold" },
      { token: "method.defaultLibrary", foreground: "B45309", fontStyle: "italic" },
      { token: "parameter", foreground: "1D4ED8" },
      { token: "parameter.declaration", foreground: "1D4ED8", fontStyle: "bold" },
      { token: "property", foreground: "0F766E" },
      { token: "property.declaration", foreground: "0F766E", fontStyle: "bold" },
      { token: "property.readonly", foreground: "9A3412", fontStyle: "bold" },
      { token: "enumMember", foreground: "9A3412", fontStyle: "bold" },
      { token: "enumMember.declaration", foreground: "9A3412", fontStyle: "bold" },
      { token: "variable", foreground: "46556F" },
      { token: "variable.declaration", foreground: "46556F", fontStyle: "bold" },
      { token: "variable.local", foreground: "46556F" },
      { token: "variable.defaultLibrary", foreground: "C2410C", fontStyle: "italic" },
      { token: "namespace.declaration", foreground: "7C3AED", fontStyle: "bold" },
      { token: "variable.readonly", foreground: "9A3412", fontStyle: "bold" },
      { token: "decorator", foreground: "7C3AED" },
      { token: "tag", foreground: "C2410C" },
      { token: "attribute.name", foreground: "0F5CC0" },
      { token: "attribute.value", foreground: "0F766E" },
      { token: "metatag", foreground: "B45309" },
      { token: "metatag.content", foreground: "475467" },
    ],
    colors: {
      "editor.background": "#FBFBFD",
      "editor.foreground": "#1F2937",
      "editor.lineHighlightBackground": "#F2F6FC",
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground": "#CFE3FF",
      "editor.inactiveSelectionBackground": "#E7EFFB",
      "editor.wordHighlightBackground": "#D7E8FF80",
      "editor.wordHighlightBorder": "#87B4FF",
      "editor.wordHighlightStrongBackground": "#FFE4A880",
      "editor.wordHighlightStrongBorder": "#FFB54A",
      "editor.findMatchBackground": "#FFE6A3",
      "editor.findMatchBorder": "#C98000",
      "editor.findMatchHighlightBackground": "#FFF3CC",
      "editor.findMatchHighlightBorder": "#D8B15A",
      "editor.findRangeHighlightBackground": "#FFF7D699",
      "editor.findRangeHighlightBorder": "#F1D48B",
      "editor.selectionHighlightBackground": "#E2EEFFAA",
      "editor.selectionHighlightBorder": "#A9C8FF",
      "editorCursor.foreground": "#005BD4",
      "editorLineNumber.foreground": "#A0A8B8",
      "editorLineNumber.activeForeground": "#516079",
      "editorIndentGuide.background1": "#E5EAF2",
      "editorIndentGuide.activeBackground1": "#BAC5D6",
      "editorBracketMatch.background": "#E6F0FF",
      "editorBracketMatch.border": "#8AAEF8",
      "editorWhitespace.foreground": "#D7DCE5",
      "editorGutter.background": "#FBFBFD",
      "scrollbarSlider.background": "#C7CFDD66",
      "scrollbarSlider.hoverBackground": "#95A2B866",
      "scrollbarSlider.activeBackground": "#6C7B9566",
      "minimap.background": "#FBFBFD",
      "editorOverviewRuler.findMatchForeground": "#C9800099",
    },
  });
}
