import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { redactSecrets } from "./secretRedaction.js";
import type { ContextManifestAttempt, ContextManifestV1 } from "./contextManifest.js";
import { evaluateContextPath } from "./contextPolicy.js";
import { isProcessAlive } from "../utils/processLiveness.js";

const MANIFEST_DIR = path.join(".history", "context-manifests");
const PREFERENCES_DIR = path.join(".history", "context-preferences");
const ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,199}$/;
const MAX_MANIFESTS = 10_000;

export interface ContextPin { id: string; path: string; reason?: string; createdAt: number; }
export interface ContextPreferencesV1 { schemaVersion: 1; conversationId: string; version: number; pins: ContextPin[]; excludes: string[]; updatedAt: number; }
export class ContextPreferencesVersionConflictError extends Error { constructor(readonly current: ContextPreferencesV1) { super("Context preferences version conflict"); } }
export class ContextPersistenceError extends Error { readonly code = "context_persistence_invalid"; constructor(readonly filePath: string, cause?: unknown) { super(`Context persistence is invalid or unreadable: ${path.basename(filePath)}`, { cause }); } }

function root(workspace: string): string { return fs.realpathSync.native(path.resolve(workspace)); }
function manifestDir(workspace: string): string { const dir = path.join(root(workspace), MANIFEST_DIR); fs.mkdirSync(dir, { recursive: true }); return dir; }
function manifestPath(workspace: string, id: string): string { if (!ID.test(id)) throw new Error("Invalid context manifest id"); return path.join(manifestDir(workspace), `${id}.json`); }
function preferencesPath(workspace: string, conversationId: string): string { if (!ID.test(conversationId)) throw new Error("Invalid conversation id"); const dir = path.join(root(workspace), PREFERENCES_DIR); fs.mkdirSync(dir, { recursive: true }); return path.join(dir, `${conversationId}.json`); }
function atomicWrite(file: string, value: unknown): void { const temp = `${file}.${process.pid}.${crypto.randomUUID()}.tmp`; fs.writeFileSync(temp, `${JSON.stringify(redactSecrets(value), null, 2)}\n`, { encoding: "utf8", flag: "wx" }); fs.renameSync(temp, file); }
function withLock<T>(target: string, operation: () => T): T { const lock = `${target}.lock`; const token = crypto.randomUUID(); let fd: number | undefined; const deadline = Date.now() + 2_000; while (Date.now() <= deadline) { try { fd = fs.openSync(lock, "wx"); fs.writeFileSync(fd, JSON.stringify({ pid: process.pid, token, createdAt: Date.now() })); break; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; try { const owner = JSON.parse(fs.readFileSync(lock, "utf8")) as { pid?: number; createdAt?: number }; if (owner.pid && !isProcessAlive(owner.pid) && Date.now() - (owner.createdAt || 0) > 1_000) fs.rmSync(lock, { force: true }); } catch { try { if (Date.now() - fs.statSync(lock).mtimeMs > 60_000) fs.rmSync(lock, { force: true }); } catch { /* retry */ } } Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 5); } } if (fd === undefined) throw new Error("Context manifest store is busy"); try { return operation(); } finally { fs.closeSync(fd); try { const owner = JSON.parse(fs.readFileSync(lock, "utf8")) as { token?: string }; if (owner.token === token) fs.rmSync(lock, { force: true }); } catch { /* ownership changed */ } } }

function isManifest(value: unknown): value is ContextManifestV1 { const x = value as Partial<ContextManifestV1>; return Boolean(x && x.schemaVersion === 1 && typeof x.manifestId === "string" && typeof x.logicalRequestId === "string" && Array.isArray(x.items) && Array.isArray(x.attempts)); }
export function readContextManifest(workspace: string, id: string): ContextManifestV1 { const file = manifestPath(workspace, id); let value: unknown; try { value = JSON.parse(fs.readFileSync(file, "utf8")); } catch (error) { throw new ContextPersistenceError(file, error); } if (!isManifest(value) || value.manifestId !== id) throw new ContextPersistenceError(file); return structuredClone(value); }
export function prepareContextManifest(workspace: string, manifest: ContextManifestV1): ContextManifestV1 { const file = manifestPath(workspace, manifest.manifestId); if (fs.existsSync(file)) throw new Error("Context manifest already exists"); atomicWrite(file, manifest); prune(workspace); return structuredClone(manifest); }
export function updateContextManifest(workspace: string, id: string, mutate: (manifest: ContextManifestV1) => void): ContextManifestV1 { const file = manifestPath(workspace, id); return withLock(file, () => { const manifest = readContextManifest(workspace, id); mutate(manifest); manifest.updatedAt = Date.now(); atomicWrite(file, manifest); return structuredClone(manifest); }); }
export function listContextManifests(workspace: string, filter: { runId?: string; conversationId?: string; requestId?: string } = {}): ContextManifestV1[] { return fs.readdirSync(manifestDir(workspace)).filter((name) => name.endsWith(".json")).map((name) => readContextManifest(workspace, name.slice(0, -5))).filter((item) => (!filter.runId || item.runId === filter.runId) && (!filter.conversationId || item.conversationId === filter.conversationId) && (!filter.requestId || item.requestId === filter.requestId)).sort((a, b) => b.updatedAt - a.updatedAt); }
function prune(workspace: string): void { const files = fs.readdirSync(manifestDir(workspace)).filter((name) => name.endsWith(".json")).map((name) => ({ name, mtime: fs.statSync(path.join(manifestDir(workspace), name)).mtimeMs })).sort((a, b) => b.mtime - a.mtime); for (const item of files.slice(MAX_MANIFESTS)) fs.rmSync(path.join(manifestDir(workspace), item.name), { force: true }); }

export function startContextManifestAttempt(workspace: string, id: string, attempt: number): ContextManifestV1 { return updateContextManifest(workspace, id, (manifest) => { manifest.status = "sent"; manifest.attempts.push({ attempt, startedAt: Date.now(), status: "sent" }); }); }
export function finishContextManifestAttempt(workspace: string, id: string, input: { attempt: number; status: ContextManifestAttempt["status"]; httpStatus?: number; errorCode?: string; actualPromptTokens?: number }): ContextManifestV1 { return updateContextManifest(workspace, id, (manifest) => { let target: ContextManifestAttempt | undefined; for (let index = manifest.attempts.length - 1; index >= 0; index -= 1) if (manifest.attempts[index].attempt === input.attempt) { target = manifest.attempts[index]; break; } if (!target) throw new Error("Context manifest attempt is missing"); target.status = input.status; target.endedAt = Date.now(); if (input.httpStatus !== undefined) target.httpStatus = input.httpStatus; if (input.errorCode) target.errorCode = redactSecrets(input.errorCode).slice(0, 100); if (input.actualPromptTokens !== undefined) manifest.actualPromptTokens = Math.max(0, input.actualPromptTokens); manifest.status = input.status === "completed" ? "completed" : input.status === "aborted" ? "aborted" : input.status === "failed" ? "failed" : "sent"; if (input.errorCode && (input.status === "failed" || input.status === "aborted")) manifest.errorCode = redactSecrets(input.errorCode).slice(0, 100); }); }

function normalizeRelative(value: unknown): string | null { if (typeof value !== "string") return null; const normalized = value.trim().replace(/\\/g, "/").replace(/^\.\//, ""); if (!normalized || normalized.length > 1000 || path.posix.isAbsolute(normalized) || normalized.split("/").some((part) => !part || part === "." || part === "..")) return null; return normalized; }
export function readContextPreferences(workspace: string, conversationId: string): ContextPreferencesV1 { const file = preferencesPath(workspace, conversationId); let x: Partial<ContextPreferencesV1>; try { x = JSON.parse(fs.readFileSync(file, "utf8")) as Partial<ContextPreferencesV1>; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { schemaVersion: 1, conversationId, version: 0, pins: [], excludes: [], updatedAt: 0 }; throw new ContextPersistenceError(file, error); } if (x.schemaVersion === 1 && x.conversationId === conversationId && Number.isSafeInteger(x.version) && Array.isArray(x.pins) && Array.isArray(x.excludes)) return x as ContextPreferencesV1; throw new ContextPersistenceError(file); }
export function updateContextPreferences(workspace: string, conversationId: string, input: { expectedVersion: number; pins?: Array<{ id?: string; path: string; reason?: string }>; excludes?: string[] }): ContextPreferencesV1 { const file = preferencesPath(workspace, conversationId); return withLock(file, () => { const current = readContextPreferences(workspace, conversationId); if (!Number.isSafeInteger(input.expectedVersion) || input.expectedVersion !== current.version) throw new ContextPreferencesVersionConflictError(current); const pins = input.pins === undefined ? current.pins : input.pins.map((entry) => { const relative = normalizeRelative(entry.path); const policy = relative ? evaluateContextPath(relative) : undefined; if (!relative || !policy?.allowed) throw new Error(`Context pin is not authorized: ${policy?.reason || "invalid_path"}`); return { id: typeof entry.id === "string" && ID.test(entry.id) ? entry.id : `pin-${crypto.randomUUID()}`, path: relative, ...(typeof entry.reason === "string" && entry.reason.trim() ? { reason: redactSecrets(entry.reason.trim()).slice(0, 500) } : {}), createdAt: Date.now() }; }).slice(0, 100); const excludes = input.excludes === undefined ? current.excludes : [...new Set(input.excludes.map((entry) => { if (typeof entry !== "string" || !entry.trim() || entry.length > 500 || entry.includes("\0")) throw new Error("Invalid context exclude pattern"); return entry.trim(); }))].slice(0, 200); const next: ContextPreferencesV1 = { schemaVersion: 1, conversationId, version: current.version + 1, pins, excludes, updatedAt: Date.now() }; atomicWrite(file, next); return structuredClone(next); }); }
