#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CSS_FILE="$ROOT_DIR/frontend/src/App.css"
APP_FILE="$ROOT_DIR/frontend/src/App.tsx"
COMMAND_FILE="$ROOT_DIR/frontend/src/components/CommandPalette.tsx"
SEARCH_FILE="$ROOT_DIR/frontend/src/components/WorkspaceSearchPanel.tsx"
SIDEBAR_FILE="$ROOT_DIR/frontend/src/components/Sidebar.tsx"
LOGIN_FILE="$ROOT_DIR/frontend/src/components/LoginPage.tsx"
SETTINGS_FILE="$ROOT_DIR/frontend/src/components/SettingsModal.tsx"
AUTH_ROUTE_FILE="$ROOT_DIR/backend/src/routes/auth.ts"
TREE_FILE="$ROOT_DIR/frontend/src/components/FileTree.tsx"
CHAT_FILE="$ROOT_DIR/frontend/src/components/ChatPanel.tsx"
TASK_HEADER_FILE="$ROOT_DIR/frontend/src/components/TaskHeader.tsx"
BUILTIN_PLUGIN_FILE="$ROOT_DIR/frontend/src/plugins/builtin/index.ts"
JSON_PREVIEW_FILE="$ROOT_DIR/frontend/src/plugins/builtin/jsonPreviewPlugin.tsx"
CHECKPOINT_FILE="$ROOT_DIR/frontend/src/components/CheckpointPanel.tsx"
PROBLEMS_FILE="$ROOT_DIR/frontend/src/components/ProblemsPanel.tsx"
RUN_CENTER_FILE="$ROOT_DIR/frontend/src/components/RunCenterPanel.tsx"
DEBUG_FILE="$ROOT_DIR/frontend/src/components/DebugPanel.tsx"
APPROVAL_FILE="$ROOT_DIR/frontend/src/components/ToolApprovalCard.tsx"
CHANGE_SUMMARY_FILE="$ROOT_DIR/frontend/src/components/ChangeSummary.tsx"
CHANGE_DIFF_FILE="$ROOT_DIR/frontend/src/components/ChangeDiffDialog.tsx"
GIT_FILE="$ROOT_DIR/frontend/src/components/GitPanel.tsx"
TAB_FILE="$ROOT_DIR/frontend/src/components/TabBar.tsx"
PANEL_CHROME_FILE="$ROOT_DIR/frontend/src/components/PanelChrome.tsx"
AGENT_BOARD_FILE="$ROOT_DIR/frontend/src/components/AgentBoard.tsx"
TEAM_FILE="$ROOT_DIR/frontend/src/components/TeamPanel.tsx"
TERMINAL_FILE="$ROOT_DIR/frontend/src/components/Terminal.tsx"
CHAT_WS_FILE="$ROOT_DIR/backend/src/ws/chat.ts"
REVIEW_FINDINGS_FILE="$ROOT_DIR/backend/src/chat/reviewFindings.ts"

assert_contains() {
  local file="$1"
  local pattern="$2"
  local description="$3"

  if ! rg -q --fixed-strings "$pattern" "$file"; then
    echo "UI contract failed: $description" >&2
    echo "  expected '$pattern' in $file" >&2
    exit 1
  fi
}

assert_contains "$CSS_FILE" ".panel-shell" "shared panel shell"
assert_contains "$CSS_FILE" "@media (max-width: 860px)" "narrow-screen drawer breakpoint"
assert_contains "$CSS_FILE" "@media (max-width: 720px)" "compact modal breakpoint"
assert_contains "$CSS_FILE" "@media (prefers-reduced-motion: reduce)" "reduced-motion support"
assert_contains "$CSS_FILE" "[role=\"tab\"]:focus-visible" "visible tab focus"
assert_contains "$APP_FILE" "aria-modal=\"true\"" "diff dialog semantics"
assert_contains "$APP_FILE" "handleEscape" "global Escape handling"
assert_contains "$COMMAND_FILE" "aria-modal=\"true\"" "command dialog semantics"
assert_contains "$SEARCH_FILE" "aria-modal=\"true\"" "search dialog semantics"
assert_contains "$SIDEBAR_FILE" "sidebar-search" "explorer inline filter"
assert_contains "$SIDEBAR_FILE" "sidebar-workspace-card" "explorer workspace identity"
assert_contains "$SIDEBAR_FILE" "folderBrowser.selectable" "allowed workspace selection boundary"
assert_contains "$SIDEBAR_FILE" "folderBrowser.switching" "workspace switching feedback"
assert_contains "$APP_FILE" 'key={`git:${workspaceDir}`}' "workspace-scoped Git panel reset"
assert_contains "$LOGIN_FILE" "login-mode-tabs" "local login and registration switch"
assert_contains "$AUTH_ROUTE_FILE" '/register' "public registration endpoint"
assert_contains "$SETTINGS_FILE" "pendingRegistrations" "administrator registration review queue"
assert_contains "$TREE_FILE" "role=\"treeitem\"" "keyboard-accessible file tree items"
assert_contains "$SIDEBAR_FILE" "handleRootContextMenu" "workspace-root context menu"
assert_contains "$SIDEBAR_FILE" "sidebar.uploadFiles" "root context upload action"
assert_contains "$SIDEBAR_FILE" "sidebar.copyItem" "file and folder copy action"
assert_contains "$SIDEBAR_FILE" "sidebar.pasteItem" "folder and workspace-root paste action"
assert_contains "$SIDEBAR_FILE" "onCopyEntry" "Explorer copy API integration"
assert_contains "$TREE_FILE" "onDropFiles" "directory-targeted file drop"
assert_contains "$TREE_FILE" "useState(false)" "collapsed-by-default file tree"
assert_contains "$CHAT_FILE" "detailsCollapsed" "collapsible AI task controls"
assert_contains "$TASK_HEADER_FILE" "aria-expanded={!detailsCollapsed}" "accessible task control toggle"
assert_contains "$BUILTIN_PLUGIN_FILE" "jsonPreviewPlugin" "builtin JSON visualizer registration"
assert_contains "$JSON_PREVIEW_FILE" "builtin.json-preview" "builtin JSON visualizer manifest"
assert_contains "$JSON_PREVIEW_FILE" "role=\"tree\"" "accessible JSON tree"
assert_contains "$JSON_PREVIEW_FILE" '"editor.modify"' "permission-gated JSON hierarchy editing"
assert_contains "$JSON_PREVIEW_FILE" "addJsonChild" "JSON child insertion"
assert_contains "$JSON_PREVIEW_FILE" "renameJsonKey" "JSON object key rename"
assert_contains "$JSON_PREVIEW_FILE" "deleteJsonNode" "JSON node deletion"
assert_contains "$JSON_PREVIEW_FILE" "handleUndo" "reversible JSON hierarchy operations"
assert_contains "$JSON_PREVIEW_FILE" "aria-modal=\"true\"" "accessible JSON mutation dialog"
assert_contains "$CSS_FILE" ".json-preview" "JSON visualizer theme surface"
assert_contains "$CSS_FILE" ".json-preview-dialog" "JSON hierarchy editor dialog surface"
assert_contains "$CSS_FILE" ".terminal-resize-handle" "resizable terminal handle"
assert_contains "$APP_FILE" "aria-valuenow={terminalHeight}" "keyboard-accessible terminal resize"
assert_contains "$CSS_FILE" "landing-scroll" "scrollable landing page root"
assert_contains "$APP_FILE" "editor-compare-workbench" "side-by-side file comparison workspace"
assert_contains "$CSS_FILE" ".editor-compare-workbench" "responsive comparison layout"
assert_contains "$CSS_FILE" ".workbench-view-files .editor-compare-picker" "visible editor-first comparison control"
assert_contains "$CSS_FILE" ":not(.editor-compare-picker):not(.editor-compare-sync):not(.editor-compare-close)" "comparison controls excluded from hidden legacy actions"
assert_contains "$APP_FILE" "toggleUtilityPanel" "mutually exclusive workbench utility panels"
assert_contains "$APP_FILE" "toggleExplorerPanel" "Explorer and utility panel exclusivity"
assert_contains "$APP_FILE" "window.innerWidth <= 860" "single narrow-screen utility drawer"
assert_contains "$APP_FILE" "titlebar-mobile-command" "touch-accessible compact command entry"
assert_contains "$COMMAND_FILE" "command.openCheckpoints" "checkpoint command palette entry"
assert_contains "$COMMAND_FILE" "command.openProblems" "Problems command palette entry"
assert_contains "$COMMAND_FILE" "command.openRunCenter" "Run and Test command palette entry"
assert_contains "$COMMAND_FILE" "command.openDebug" "Run and Debug command palette entry"
assert_contains "$CHAT_WS_FILE" "initialTurn.mode === \"code\"" "server-enforced pre-code checkpoint"
assert_contains "$CHAT_WS_FILE" "createCheckpoint(session.workspaceDir" "automatic pre-code checkpoint"
assert_contains "$CHECKPOINT_FILE" "checkpoint.restoreConfirm" "explicit checkpoint restore confirmation"
assert_contains "$PROBLEMS_FILE" "onOpenLocation(problem)" "problem-to-editor navigation"
assert_contains "$RUN_CENTER_FILE" "onOpenLocation(failure)" "test-failure-to-editor navigation"
assert_contains "$RUN_CENTER_FILE" "center.stop(active.id)" "cancellable run task control"
assert_contains "$PROBLEMS_FILE" "diagnostics.startWatching()" "persistent diagnostics session control"
assert_contains "$DEBUG_FILE" "debug.command(\"step_over\")" "debugger step control"
assert_contains "$DEBUG_FILE" "debug.session.frames" "debugger call stack"
assert_contains "$DEBUG_FILE" 'return "python"' "Python debug target recognition"
assert_contains "$DEBUG_FILE" "debug.status.startingPython" "Python debugger status feedback"
assert_contains "$DEBUG_FILE" "debug.noTarget" "actionable empty debug target feedback"
assert_contains "$APPROVAL_FILE" "allow_session" "session-scoped tool approval"
assert_contains "$APPROVAL_FILE" "allow_once" "per-action tool approval"
assert_contains "$CSS_FILE" ".checkpoint-panel" "checkpoint panel responsive surface"
assert_contains "$CSS_FILE" ".problems-panel" "Problems panel responsive surface"
assert_contains "$CSS_FILE" ".run-center-panel" "Run and Test panel responsive surface"
assert_contains "$CSS_FILE" ".debug-panel" "Run and Debug panel responsive surface"
assert_contains "$CHAT_FILE" "<ChangeSummary" "single stable task change summary"
assert_contains "$CHANGE_SUMMARY_FILE" "onOpenLocation(finding)" "review finding to editor navigation"
assert_contains "$CHANGE_SUMMARY_FILE" "onOpenDiff(path)" "task summary to Git diff navigation"
assert_contains "$CHANGE_DIFF_FILE" "<DiffEditor" "Monaco change review canvas"
assert_contains "$CHANGE_DIFF_FILE" "aria-modal=\"true\"" "accessible Git diff dialog"
assert_contains "$GIT_FILE" "git.group.conflicted" "understandable conflict group"
assert_contains "$GIT_FILE" "git.group.untracked" "understandable untracked group"
assert_contains "$TAB_FILE" 'event.key === "ArrowRight"' "keyboard tab navigation"
assert_contains "$TAB_FILE" "tab-path" "disambiguated tab paths"
assert_contains "$REVIEW_FINDINGS_FILE" "parseReviewFindings" "structured review finding parser"
assert_contains "$PANEL_CHROME_FILE" "PanelHeader" "shared collaboration panel header"
assert_contains "$PANEL_CHROME_FILE" "PanelState" "shared loading, empty, error and disabled states"
assert_contains "$CSS_FILE" "@media (max-width: 1100px)" "1024px workspace drawer layout"
assert_contains "$APP_FILE" "activeWorkspaceDrawer" "single responsive workspace drawer"
assert_contains "$APP_FILE" "drawerTriggerRef" "drawer focus return"
assert_contains "$APP_FILE" "closeWorkspaceDrawers" "shared drawer dismissal"
assert_contains "$AGENT_BOARD_FILE" 'data-workspace-drawer="agents"' "accessible Agent Board drawer"
assert_contains "$TEAM_FILE" 'data-workspace-drawer="team"' "accessible Team drawer"
assert_contains "$TERMINAL_FILE" 'data-workspace-drawer="terminal"' "accessible terminal drawer"
assert_contains "$TERMINAL_FILE" "terminal.reconnect" "terminal reconnect action"
assert_contains "$TERMINAL_FILE" "prefers-reduced-motion" "reduced-motion terminal cursor"

echo "CrownForge UI contract passed."
